/**
 * HammerWarmupDialog — opens the WarmupGeneratorCard in a dialog from the
 * Hammer Today plan, then adds the generated warm-up directly to today's
 * Game Plan via the existing custom_activity_templates mechanics. Zero
 * parallel storage; mirrors the "Add to Game Plan" flow in HammerDailyPlan.
 */
import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { WarmupGeneratorCard } from "@/components/custom-activities/WarmupGeneratorCard";
import { useCustomActivities } from "@/hooks/useCustomActivities";
import { useAuth } from "@/hooks/useAuth";
import type { Exercise, CustomActivityTemplate } from "@/types/customActivity";

interface HammerWarmupDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  sport: "baseball" | "softball";
}

export function HammerWarmupDialog({ open, onOpenChange, sport }: HammerWarmupDialogProps) {
  const { user } = useAuth();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { createTemplate } = useCustomActivities(sport);
  const [saving, setSaving] = useState(false);

  async function handleAddWarmup(warmupExercises: Exercise[]) {
    if (!user) {
      toast.error("Sign in to add a warm-up.");
      return;
    }
    if (saving) return;
    setSaving(true);
    try {
      const totalMin = warmupExercises.reduce((sum, e) => {
        const d = Number((e as { duration_minutes?: number }).duration_minutes ?? 0);
        return sum + (Number.isFinite(d) ? d : 0);
      }, 0);
      const payload = {
        activity_type: "warmup",
        title: "Hammer warm-up",
        description: "Personalized warm-up generated by Hammer.",
        icon: "flame",
        color: "#f97316",
        exercises: warmupExercises,
        meals: {} as never,
        custom_fields: [],
        duration_minutes: totalMin > 0 ? totalMin : null,
        intensity: null,
        distance_value: null,
        distance_unit: null,
        pace_value: null,
        intervals: [],
        is_favorited: false,
        is_non_negotiable: false,
        source: "hammer.daily.warmup",
        recurring_days: [],
        recurring_active: false,
        sport,
        embedded_running_sessions: null,
        display_nickname: null,
        custom_logo_url: null,
        reminder_enabled: false,
        reminder_time: null,
        display_on_game_plan: true,
        display_days: [],
        display_time: null,
        specific_dates: null,
      } as unknown as Omit<
        CustomActivityTemplate,
        "id" | "user_id" | "created_at" | "updated_at"
      >;
      const result = await createTemplate(payload, true);
      if (!result) return;
      try {
        const bc = new BroadcastChannel("data-sync");
        bc.postMessage({ type: "custom-activity-updated", templateId: result.id });
        bc.close();
      } catch {
        /* realtime will catch up */
      }
      queryClient.invalidateQueries({ queryKey: ["custom-activity-logs"] });
      queryClient.invalidateQueries({ queryKey: ["custom-activity-templates"] });
      queryClient.invalidateQueries({ queryKey: ["game-plan"] });
      toast.success("Warm-up added to today's Game Plan", {
        action: {
          label: "View",
          onClick: () => navigate("/dashboard#game-plan"),
        },
      });
      onOpenChange(false);
    } catch (e) {
      console.error("[HammerWarmupDialog] add warm-up failed", e);
      toast.error(e instanceof Error ? e.message : "Couldn't add warm-up");
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Warm up with Hammer</DialogTitle>
        </DialogHeader>
        <WarmupGeneratorCard
          exercises={[]}
          isWarmupActivity
          sport={sport}
          onAddWarmup={handleAddWarmup}
        />
      </DialogContent>
    </Dialog>
  );
}
