/**
 * CardActions — shared "Add to game plan" + "Ask Hammer" footer for the
 * canonical WK cards (Speed, Bat Speed, Lifts, Conditioning).
 *
 * Mirrors the HammerDailyPlan block-level actions so every daily card exposes
 * the same two affordances the athlete expects. Zero parallel storage —
 * templates go through `useCustomActivities.createTemplate` and the chat uses
 * the canonical `useHammerChat` hook.
 */
import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { CalendarPlus, CheckCircle2, MessageCircle, Send } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useCustomActivities } from "@/hooks/useCustomActivities";
import { useHammerChat } from "@/hooks/useHammerChat";
import { useHammerAthleteContext } from "@/lib/hammer/context/athleteContext";
import type { CustomActivityTemplate } from "@/types/customActivity";
import type { WkRx } from "@/hooks/useWkDailyPrescriptions";

type Modality = "speed" | "bat_speed" | "lifts" | "conditioning";

const MOD_META: Record<Modality, {
  title: string;
  activityType: string;
  icon: string;
  color: string;
  source: string;
  hierarchyId: string;
}> = {
  speed: {
    title: "Hammer Speed",
    activityType: "speed",
    icon: "zap",
    color: "#8b5cf6",
    source: "hammer.daily.speed",
    hierarchyId: "hammer.daily.speed",
  },
  bat_speed: {
    title: "Hammer Bat Speed",
    activityType: "hitting",
    icon: "bolt",
    color: "#d946ef",
    source: "hammer.daily.bat_speed",
    hierarchyId: "hammer.daily.bat_speed",
  },
  lifts: {
    title: "Hammer Lifts",
    activityType: "strength",
    icon: "dumbbell",
    color: "#3b82f6",
    source: "hammer.daily.lifts",
    hierarchyId: "hammer.daily.lifts",
  },
  conditioning: {
    title: "Hammer Conditioning",
    activityType: "conditioning",
    icon: "heart",
    color: "#10b981",
    source: "hammer.daily.conditioning",
    hierarchyId: "hammer.daily.conditioning",
  },
};

interface Props {
  modality: Modality;
  items: WkRx[];
  phaseDisplay?: string | null;
}

export function CardActions({ modality, items, phaseDisplay }: Props) {
  const { user } = useAuth();
  const ctx = useHammerAthleteContext();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const sport = (ctx.get<string>("sport_primary")?.value as
    | "baseball"
    | "softball"
    | undefined) ?? "baseball";
  const { createTemplate } = useCustomActivities(sport);
  const [adding, setAdding] = useState(false);
  const [added, setAdded] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);

  const meta = MOD_META[modality];
  const displayTitle = phaseDisplay ? `${meta.title} — ${phaseDisplay}` : meta.title;

  async function handleAdd() {
    if (adding || added) return;
    if (!user) return toast.error("Sign in to add to your Game Plan.");
    if (items.length === 0) return;
    setAdding(true);
    try {
      const totalMin = items.reduce((sum, r) => {
        const sets = Number(r.sets ?? 0);
        return sum + (Number.isFinite(sets) ? sets : 0);
      }, 0);
      const payload = {
        activity_type: meta.activityType,
        title: displayTitle,
        description: `Personalized ${modality.replace("_", " ")} block generated by Hammer.`,
        icon: meta.icon,
        color: meta.color,
        exercises: [],
        meals: {} as never,
        custom_fields: items.map((r, i) => ({
          id: `wk-${i}`,
          label: r.movement_name,
          value: [
            r.sets ? `${r.sets} × ${r.reps ?? "-"}` : null,
            r.tempo ? `Tempo ${r.tempo}` : null,
            r.load_pct ? `${r.load_pct}%` : null,
          ].filter(Boolean).join(" · "),
          notes: r.why_payload?.cue ?? r.rationale ?? "",
        })),
        duration_minutes: totalMin > 0 ? totalMin * 2 : null,
        intensity: null,
        distance_value: null,
        distance_unit: null,
        pace_value: null,
        intervals: [],
        is_favorited: false,
        is_non_negotiable: false,
        source: meta.source,
        recurring_days: [],
        recurring_active: false,
        sport,
        embedded_running_sessions: null,
        display_nickname: null,
        custom_logo_url: null,
        reminder_enabled: false,
        reminder_time: null,
        display_on_game_plan: true,
        display_days: [],
        display_time: null,
        specific_dates: null,
      } as unknown as Omit<
        CustomActivityTemplate,
        "id" | "user_id" | "created_at" | "updated_at"
      >;
      const result = await createTemplate(payload, true);
      if (!result) return;
      setAdded(true);
      try {
        const bc = new BroadcastChannel("data-sync");
        bc.postMessage({ type: "custom-activity-updated", templateId: result.id });
        bc.close();
      } catch {
        /* realtime will catch up */
      }
      queryClient.invalidateQueries({ queryKey: ["custom-activity-logs"] });
      queryClient.invalidateQueries({ queryKey: ["custom-activity-templates"] });
      queryClient.invalidateQueries({ queryKey: ["game-plan"] });
      toast.success(`${meta.title} added to today's Game Plan`, {
        action: { label: "View", onClick: () => navigate("/dashboard#game-plan") },
      });
    } catch (e) {
      console.error("[CardActions] add to game plan failed", e);
      toast.error(e instanceof Error ? e.message : "Couldn't add to Game Plan");
    } finally {
      setAdding(false);
    }
  }

  return (
    <div className="pt-2 border-t border-border/40 space-y-2">
      <div className="flex items-center gap-2 flex-wrap">
        <Button
          size="sm"
          variant="secondary"
          onClick={handleAdd}
          disabled={adding || added || items.length === 0}
          className="text-xs gap-1"
        >
          {added ? (
            <><CheckCircle2 className="h-3 w-3" /> Added</>
          ) : (
            <><CalendarPlus className="h-3 w-3" />{adding ? "Adding…" : "Add to game plan"}</>
          )}
        </Button>
        <Button
          size="sm"
          variant="ghost"
          onClick={() => setChatOpen((v) => !v)}
          className="text-xs gap-1"
        >
          <MessageCircle className="h-3 w-3" />
          {chatOpen ? "Close chat" : "Ask Hammer"}
        </Button>
      </div>
      {chatOpen && <MiniChat modality={modality} items={items} meta={meta} />}
    </div>
  );
}

function MiniChat({
  modality,
  items,
  meta,
}: {
  modality: Modality;
  items: WkRx[];
  meta: (typeof MOD_META)[Modality];
}) {
  const chat = useHammerChat({
    categoryFocus: {
      id: meta.hierarchyId,
      name: meta.title,
      hierarchyRank: "rank_1",
      whyItMatters: `Athlete's ${modality.replace("_", " ")} block today.`,
      howToImprove: items
        .map((r) => `${r.movement_name}${r.sets ? ` (${r.sets}×${r.reps ?? "-"})` : ""}${r.why_payload?.cue ? ` — ${r.why_payload.cue}` : ""}`)
        .join("; "),
    },
  });
  const [text, setText] = useState("");

  async function handleSend() {
    if (!text.trim() || chat.isSending) return;
    const t = text;
    setText("");
    await chat.send(t);
  }

  return (
    <div className="rounded-md border border-border/50 bg-background p-2 space-y-2">
      <div className="max-h-48 overflow-y-auto space-y-1.5 text-xs">
        {chat.messages.length === 0 && (
          <div className="text-[11px] text-muted-foreground italic">
            Ask Hammer anything about this block — form, swaps, why it's prescribed.
          </div>
        )}
        {chat.messages.map((m, i) => (
          <div
            key={i}
            className={m.role === "user" ? "text-foreground" : "text-foreground bg-muted/40 rounded p-1.5"}
          >
            <span className="text-[10px] uppercase tracking-wider text-muted-foreground mr-1">
              {m.role === "user" ? "You" : "Hammer"}
            </span>
            {m.content}
          </div>
        ))}
        {chat.isSending && (
          <div className="text-[11px] text-muted-foreground italic">Hammer is thinking…</div>
        )}
        {chat.error && <div className="text-[11px] text-destructive">{chat.error}</div>}
      </div>
      <div className="flex gap-1.5">
        <Textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              handleSend();
            }
          }}
          placeholder="Ask about this block…"
          className="min-h-[36px] text-xs resize-none"
          rows={1}
        />
        <Button size="sm" onClick={handleSend} disabled={!text.trim() || chat.isSending} className="h-9 px-2">
          <Send className="h-3 w-3" />
        </Button>
      </div>
    </div>
  );
}
