import type { ReportCardTileSpec } from "./types";

/** Display language only. The measured tile and its stored diagnostic values are unchanged. */
const HITTING: Record<string, [string, string, string]> = {
  hip_load: ["Balance on the back leg while you load.", "Your back side needs to stay balanced through the load. If it gives way early, the head and hips can drift toward the pitcher before you turn.", "Load into the back hip and keep the back heel planted until the swing starts."],
  hand_load: ["Set your hands behind your head as you load.", "Hands set behind your head give the back elbow room to lead. Hand depth alone is not a grade.", "Set your hands behind your head and keep the grip together before you stride."],
  p2_timing: ["Finish setting your hands before the pitch is on its way.", "Being set early is fine. Still moving your hands as the pitch arrives makes the stride rushed.", "Get set while the pitcher prepares to deliver, then stay quiet until you move."],
  eyes_tracking: ["Keep your head with your body through the stride.", "If your head gets out ahead of your body, your back side may have released the load too early. That makes the pitch harder to see and time.", "Hold your balance over the back leg and let your head travel with your turn, not ahead of it."],
  stride_direction: ["Stride toward the pitcher.", "A straight stride gives your hips room to turn without pulling you off line.", "Land your front foot toward the pitcher and let the hips turn around a stable landing."],
  heel_plant: ["Your front heel wasn't down when you landed. Getting it on the floor gives you a stable base, sets the side bend that clears a path for your back arm to the ball, and helps keep your eyes steady.", "Your front heel touching down gives you a stable base and the side bend that clears a path for your back arm to the ball without hitting your side. It helps keep your eyes steady.", "Let your front heel settle on the floor when you land."],
  back_heel_early_rise: ["Your back heel came off the ground before your swing started. It should stay planted until the swing releases — when it lifts early, your back leg has already given up the weight.", "When your back heel lifts before the swing begins, your back leg has let go of the load early.", "Hold your back heel down through the stride; let it lift when the swing releases."],
  p3_timing: ["Get your front foot down as the pitch comes out.", "Landing on time lets you keep seeing the pitch before you turn. Rushing forward early is not the answer.", "Start your load in time to land without lunging."],
  hands_outside_shoulders_at_landing: ["Keep your hands behind the back shoulder at landing.", "Hands with room outside the back shoulder give your back elbow a path into the turn.", "Pause at landing and check that your hands have room to stay back."],
  sequencing: ["Let the hips lead the turn.", "Your hips should start the move, followed by your torso, front shoulder and lead arm. When the shoulders jump ahead, power gets lost.", "Pause at landing, turn the hips first and let the upper body follow."],
  back_elbow_contact: ["Let the back elbow gain ground while the hands stay back.", "The elbow's path toward fair territory matters more than a fixed arm angle. Hands staying back create room for the elbow to lead.", "From a quiet landing, let the elbow move forward while the hands stay with the shoulder."],
  hitters_move: ["Stay loaded, land, then let the hips and back elbow lead.", "The move works when your balance, hands, stride, landing and turn hold together. A single good piece cannot make up for a broken sequence.", "Practice the full move slowly, then bring the same order into a swing."],
  shoulder_plane_steadiness: ["Hold your shoulder plane through the turn.", "A steady shoulder plane gives the barrel a better path. This is a continuous observation, not a pass-or-fail judgment.", "Turn while keeping the shoulders on the plane they started on."],
  finish_balance: ["Finish balanced after the turn.", "Staying on your line through the finish is a useful check on the move before it. The pose at the end alone does not prove contact quality.", "Swing through and notice whether you can finish without falling away."],
  shoulder_to_shoulder_hold: ["Keep your hands back while the elbow leads.", "Holding the hands behind the back shoulder leaves room for the elbow to lead. If the front shoulder opens early, that space is lost.", "Pause at landing and keep the hands quiet while the back elbow starts forward."],
};

const SOFTBALL_HITTING: Partial<Record<string, [string, string, string]>> = {
  hip_load: ["Balance on your back leg as you load for the softball pitch.", "Keeping the back side loaded gives your head and hips a steady base while the pitcher comes through the circle.", "Load into your back hip and keep your back heel planted until the swing starts."],
  hand_load: ["Set your hands behind your head for the softball pitch.", "Hands set behind the head give the back elbow room to lead. Hand depth alone is not a grade.", "Set your hands behind your head and keep your grip together before you stride."],
  p2_timing: ["Set your hands before the softball pitcher releases.", "The underhand delivery can bring the ball in quickly. Your hands should be set before release; being ready early is fine.", "Watch the pitching arm and finish your load before the ball leaves the hand."],
  p3_timing: ["Get your front foot down as the softball pitch is released.", "A settled front foot lets you keep watching the pitch and turn without lunging. The pitcher's leg lift is not your timing cue here.", "Work from a live underhand toss and land in time to see the ball before your turn."],
  stride_direction: ["Stride toward the softball pitcher.", "On the shorter softball field, striding toward the circle keeps your body on line and gives the hips room to turn.", "Land toward the pitching circle and let your hips turn around your front side."],
  heel_plant: ["Settle your front heel at landing.", "A grounded front heel sets the side bend that clears a path for your back arm to the softball and helps keep your eyes steady on the pitch.", "Land toward the circle and let your front heel settle on the floor."],
  back_heel_early_rise: ["Keep your back heel down until your swing starts.", "The back heel rising during the stride means the back leg gave up the load before the softball swing released.", "Keep the back heel planted as you land toward the circle; let it lift when you swing."],
  eyes_tracking: ["Keep your head with your body as you stride toward the softball pitcher.", "If your head gets ahead of your body, your back side may have let go before the underhand pitch arrives.", "Hold your balance over the back leg and let your head travel with your turn."],
  hands_outside_shoulders_at_landing: ["Keep your hands behind your back shoulder when your front foot lands.", "Space behind the back shoulder lets your back elbow move freely into the softball swing.", "Check your hands at landing before you turn toward the pitch."],
  sequencing: ["Let your hips lead the softball swing.", "Your hips start the move before your torso, front shoulder and lead arm. Opening the shoulders first loses the order.", "Land toward the circle, turn your hips first and let your upper body follow."],
  back_elbow_contact: ["Let your back elbow gain ground while your hands stay back.", "The elbow moves toward fair territory while the hands wait near the shoulder; its path matters more than a fixed arm angle.", "From a quiet landing, let the elbow move before the hands chase the softball."],
  hitters_move: ["Stay loaded, land, then let your hips and back elbow lead.", "The softball swing holds together when balance, hands, stride, landing and turn work in order.", "Practice landing toward the circle before letting the hips and back elbow lead."],
  shoulder_plane_steadiness: ["Hold your shoulder plane through the softball swing.", "A steady plane gives your swing a better path. It is an observation, not a pass-or-fail judgment.", "Turn while keeping the shoulders on the plane they started on."],
  finish_balance: ["Finish balanced after the softball swing.", "Staying on your line through the finish helps show how the move held together; the finishing pose alone does not prove contact quality.", "Swing through the softball and notice whether you can finish without falling away."],
  shoulder_to_shoulder_hold: ["Keep your hands back while the back elbow leads.", "Holding space behind the back shoulder gives the elbow room to lead the softball swing.", "Pause at landing toward the circle and keep your hands quiet while the back elbow starts forward."],
};

export function coachFacingTile(tile: ReportCardTileSpec, sport: string): ReportCardTileSpec {
  const copy = sport === "softball" ? SOFTBALL_HITTING[tile.key] ?? HITTING[tile.key] : HITTING[tile.key];
  if (!copy) return tile;
  const [standard, whatWhy, howToImprove] = copy;
  return { ...tile, standard, thresholdChip: undefined,
    explainer: { whatWhy, howToImprove, encouragement: howToImprove } };
}