/** Draft coaching copy transcribed from docs/HITTING-PHILOSOPHY.md §§1, 3, 10–11.
 * Other disciplines have no authority in that document: leave their coaching fields empty.
 */
type Copy = readonly [standard: string, whatWhy: string, howToImprove: string, encouragement: string];
export const HITTING_CLIP_COPY: Record<string, Copy> = {
  "p1.hip_load": ["Load the back hip while balanced over the back leg.", "Phase 1 — Create Balance sets the back-hip position. The snapshot shows position; only the later stride and turn prove the load was held and used.", "Load the back hip before moving the hands, then keep the back side balanced through the stride.", "Build the load, then prove it in the move."],
  "p1.back_leg_balance_at_load": ["Hold the back-leg load through the stride and use it in the turn.", "Phase 1 — Create Balance is proven by what comes next: the body stays back through a real stride, then the hips lead without sliding after landing. No stride or unreadable order cannot prove the load.", "If the load was not held, rebuild back-leg balance before the stride. If it was held but not used, keep the load and let the turn begin in order.", "Let the next move prove the load."],
  "p2.hand_load": ["Set the hands behind the head after the back hip loads.", "Phase 2 — Gather draws the barrel behind the head like a bow against the loaded back hip. The load is deliberate; the later hand counter-move is not another action to cue.", "Load the hands behind the head after the back hip, before taking the power step.", "Give the back elbow room to lead."],
  "p2.hand_load_depth": ["Record your own hand-load depth without a universal target.", "Hand-load depth varies from hitter to hitter. The useful check is whether the hands set behind the head, not whether their depth matches someone else's.", "", "Your own loaded position is the reference."],
  "p2.p2_timing": ["Finish the hand load by the pitcher's peak leg lift.", "Being ready early is fine. Finishing late rushes the power step and leaves less time to judge the ball.", "Start loading the back hip and hands earlier; finish the hands while the pitcher lifts the knee.", "Being set early gives you time."],
  "p3.back_hip_socket_hold": ["Keep the back hip socket closed through landing.", "Phase 3 — Load by Stride must hold or deepen the back-hip turn created by the earlier load. Opening before Phase 4 — Hitter's Move releases the stretch too soon.", "Take the power step while holding the back hip closed; release it only when the back elbow starts forward.", "Carry the coil into the turn."],
  "p3.head_path_through_stride": ["Keep the body back as the foot goes forward.", "Head travel toward the pitcher during the stride is evidence that Phase 1 — Create Balance was not held. Lowering in place is not the same fault.", "Rebuild the back-leg load and step without letting the head chase the front foot.", "Let the foot travel, not the whole body."],
  "p3.active_stride": ["Make a deliberate power step, not a fall.", "Phase 3 — Load by Stride is voluntary. The glute reaches toward the pitcher while the body stays back; this pattern is recorded, not graded.", "Take the power step from the loaded back hip without letting gravity carry the body forward.", "Own the step."],
  "p3.stride_foot_vs_body": ["Let the front foot go forward while the body stays back.", "The stride stretches the loaded back side when the foot travels without the body gaining ground.", "Step from the loaded back hip and check that the body stays back as the foot reaches.", "Stretch without chasing the foot."],
  "p3.stride_hands_opposite": ["Keep the loaded hands back while the foot moves forward.", "Hands appearing to move back during the stride are a consequence of the body moving against a held hand load, not another hand-load cue.", "Set the hands in Phase 2 — Gather, then hold them while taking the power step.", "Let the stride create the stretch."],
  "p3.stride_side_bend": ["Build the suitcase lean as the stride unfolds.", "As the foot reaches, the chest tips toward the plate and side bend helps clear a path for the back arm.", "Hold the back-leg load and let the chest tip toward the plate as the foot reaches the floor.", "Give the back arm a clear path."],
  "p3.stride_sink": ["Sink into the back leg rather than falling forward.", "The loaded back leg can lower during Phase 3 — Load by Stride while the body stays back. Falling forward loses the coil.", "Take a controlled power step and settle over the back leg rather than traveling with the foot.", "Stay behind the step."],
  "p3.head_discipline": ["Keep the head from traveling toward the pitcher ahead of the body.", "A head moving forward beyond the body's center is a sign that Phase 1 — Create Balance was not held. A head lowering in place is allowed.", "Hold the back-leg load while stepping; let the head lower if needed without chasing the pitcher.", "Keep your view steady through the step."],
  "p3.back_heel_early_rise": ["Keep the back heel down until Phase 4 — Hitter's Move begins.", "An early back-heel rise shows the back leg let go before the swing released.", "Hold the back heel through the power step; let it rise when the swing begins.", "Stay loaded until the turn."],
  "p3.stride_direction": ["Step toward the pitcher.", "The power step sets a direction toward the pitcher instead of pulling the body off line.", "Take the step toward the pitcher and land sideways.", "Stay on your line."],
  "p3.p3_timing": ["Get the whole front foot down before the pitcher releases.", "Landing early enough gives you a moment to see the pitch before turning; landing late makes you decide and stride at once.", "Start as the pitcher strides, then finish the power step before the ball leaves the hand.", "Beat the ball with your foot."],
  "p3.back_knee_flex_maintained": ["Keep the back knee from straightening between hand load and landing.", "Straightening the back knee during Phase 3 — Load by Stride is evidence that the back leg let go of the load.", "Hold the loaded back knee's bend while stepping and landing.", "Keep the back side underneath the move."],
  "p3.heel_plant": ["Settle the front heel on the ground at landing.", "The front heel touching down stabilizes the eyes and gives the back bicep a clearer path to the ball through side bend.", "Land sideways and let the front heel reach the floor before turning.", "Land before you turn."],
  "p3.hands_outside_shoulders_at_landing": ["Keep the hands outside the back shoulder at landing.", "Hands set behind the back shoulder leave room for the back elbow to bring the barrel through.", "Set the hands behind the head, then hold them back through the step.", "Leave the elbow room to work."],
  "p3.hands_stay_up_at_plant": ["Keep the hands above the back elbow at heel landing.", "Hands dropping at landing can lose power and turn the front shoulder early. A dip in Phase 2 — Gather is allowed if the hands climb back up before landing; Phase 4 — Hitter's Move drops the barrel correctly.", "Bring the hands back above the back elbow by front-heel landing; let the barrel drop during the turn, not before.", "Set the position before the swing."],
  "p4.sequencing": ["Turn the hips before the shoulders.", "Hips-first separation is the readable proof that the loaded back side was used. When the order is too close for this clip to resolve, the check stays unproven.", "From a planted front foot, begin the move with the back elbow while the hands stay back, then let the knee, hips and shoulders follow.", "Build the order before adding speed."],
  "p4.separation_magnitude": ["Record the gap between the hip turn and shoulder turn.", "The size of the gap varies by athlete. Its magnitude alone cannot prove the order or define a universal ideal.", "", "Let your own history give this reading context."],
  "p4.shoulder_to_shoulder_hold": ["Keep the chin tucked and the front shoulder from leaking early.", "The chin-to-shoulder tuck supports ease of movement, seeing the ball and staying in sequence. Opening the front shoulder early loses that relationship.", "Hold the chin and front shoulder together into landing while the hands stay back; let the turn release in order.", "Keep the view and the sequence together."],
  "p4.back_elbow_connection": ["Move the back elbow forward while the hands stay back.", "The elbow or front of the bicep releases the loaded step. Its forward path turns the back knee and helps bring the barrel behind the ball, square to fair.", "At landing, let the back elbow begin forward and down toward the pitcher while the hands wait by the shoulder.", "Elbow first; hands follow."],
  "p4.shoulder_plane_steadiness": ["Keep the shoulder plane steady once the turn begins.", "A steady plane gives the barrel a longer path through the pitch. This is a continuous reading, not a pass-or-fail verdict.", "Turn while holding the plane the shoulders started on.", "Keep the path steady."],
  "p4.lead_elbow_bend_increasing": ["Do not bend the lead elbow more than at the end of hand load.", "Your own Phase 2 — Gather position sets the reference; a universal arm-extension target would mistake anatomy for mechanics.", "Carry your loaded lead-arm shape into the turn without adding bend.", "Use your own range, not someone else's."],
  "p4.head_vertical_movement_post_landing": ["Do not lift the head before the ball is gone.", "The head may sink after landing; rising early is the fault. Ordinary footage checks through swing peak, not the actual moment the ball leaves the bat.", "Stay with the turn without lifting your head early.", "Keep your view through the move."],
  "p4.post_landing_hip_drift": ["Rotate after landing instead of sliding toward the pitcher.", "After landing, forward hip drift shows the load was not used; absence of a slide alone does not prove a drive.", "Plant first, then turn from the loaded back side instead of carrying the hips forward.", "Turn rather than slide."],
  "finish.pelvis_rotation_efficiency": ["Face square to fair at the end of Phase 4 — Hitter's Move.", "The finish checks whether the pelvis faced toward the front of the plate after the turn. Without a settled tolerance, a recorded angle cannot be graded.", "", "Finish facing the field."],
  "finish.finish_balance": ["Finish without falling off the line.", "Balance at the finish shows whether the turn held together, but an end pose alone cannot prove contact quality.", "Swing through and check whether you can finish without falling away.", "Stay with the move through the finish."],
  "front_leg_gather.front_leg_gather": ["A front-leg gather is optional.", "The gather is a power-loading option during Phase 2 — Gather, never a requirement. It can only add, never take away.", "", "Your swing does not need a gather to be complete."],
};

export const PHASE_EXPLAINER = [
  "Phase 1 — Create Balance: load the back hip and hold weight on the back leg.",
  "Phase 2 — Gather for stability and Power : Load the bat and the front leg simultaneously",
  "Phase 3 — Load by Stride: Take a deliberate power step, Driven by the back glute to get your foot to the floor and land before the pitch leaves the hand. Momentum does not play into your stride",
  "Phase 4 — Hitter's Move: from a planted foot, the back Bicep starts forward through the ball while the knob stay back; releasing a mighty swing",
] as const;