/**
 * Tables that hold rows owned by a single user, with the column that scopes
 * ownership. Generated from the live schema (public schema, uuid columns named
 * after a user). Used only by the `delete-account` function.
 *
 * NOTE: `parent_athlete_links` appears here intentionally — deleting the link
 * rows unlinks the relationship without touching the other person's account.
 */
export const OWNED_TABLES: Array<[table: string, column: string]> = [
  ["activity_edit_logs", "user_id"],
  ["activity_folders", "owner_id"],
  ["advisory_feedback_logs", "user_id"],
  ["analysis_fault_findings", "user_id"],
  ["asb_authority_overrides", "athlete_id"],
  ["asb_events", "athlete_id"],
  ["asb_org_propagation_log", "athlete_id"],
  ["asb_state_snapshots", "athlete_id"],
  ["athlete_body_goals", "user_id"],
  ["athlete_context", "user_id"],
  ["athlete_daily_log", "user_id"],
  ["athlete_development_history_events", "user_id"],
  ["athlete_equipment_context", "user_id"],
  ["athlete_events", "user_id"],
  ["athlete_foundation_state", "user_id"],
  ["athlete_load_tracking", "user_id"],
  ["athlete_mpi_settings", "user_id"],
  ["athlete_plan_adjustments", "user_id"],
  ["athlete_professional_status", "user_id"],
  ["athlete_recruiting_consent", "athlete_id"],
  ["athlete_recruiting_consent_audit", "athlete_id"],
  ["athlete_roadmap_progress", "user_id"],
  ["athlete_side_preferences", "user_id"],
  ["audit_log", "user_id"],
  ["baserunning_daily_attempts", "user_id"],
  ["baserunning_progress", "user_id"],
  ["baserunning_splits", "user_id"],
  ["behavioral_events", "user_id"],
  ["block_workout_metrics", "user_id"],
  ["calendar_day_orders", "user_id"],
  ["calendar_events", "user_id"],
  ["calendar_skipped_items", "user_id"],
  ["catching_reps", "user_id"],
  ["checkout_attempts", "user_id"],
  ["coach_context", "user_id"],
  ["coach_grade_overrides", "coach_id"],
  ["coach_hammer_steps", "user_id"],
  ["combine_results", "user_id"],
  ["combine_sessions", "user_id"],
  ["custom_activity_logs", "user_id"],
  ["custom_activity_templates", "user_id"],
  ["cv_calibration_sessions", "user_id"],
  ["cv_velocity_measurements", "user_id"],
  ["daily_standard_checks", "user_id"],
  ["defensive_plays", "user_id"],
  ["demo_events", "user_id"],
  ["demo_leads", "user_id"],
  ["demo_progress", "user_id"],
  ["drill_assignments", "coach_id"],
  ["drill_assignments", "player_id"],
  ["drill_prescriptions", "user_id"],
  ["drill_usage_tracking", "user_id"],
  ["emotion_tracking", "user_id"],
  ["engine_adversarial_logs", "user_id"],
  ["engine_interventions", "user_id"],
  ["engine_regression_results", "user_id"],
  ["engine_sentinel_logs", "user_id"],
  ["engine_snapshot_versions", "user_id"],
  ["engine_state_predictions", "user_id"],
  ["environment_snapshots", "user_id"],
  ["folder_item_completions", "user_id"],
  ["follower_report_events", "player_id"],
  ["follower_report_logs", "player_id"],
  ["follower_reports", "player_id"],
  ["foundation_fatigue_decisions", "user_id"],
  ["foundation_onboarding_decisions", "user_id"],
  ["foundation_recommendation_traces", "user_id"],
  ["foundation_replay_outcomes", "user_id"],
  ["foundation_trigger_events", "user_id"],
  ["foundation_video_outcomes", "user_id"],
  ["game_plan_days", "user_id"],
  ["game_plan_locked_days", "user_id"],
  ["game_plan_skipped_tasks", "user_id"],
  ["game_plan_task_schedule", "user_id"],
  ["game_plan_user_preferences", "user_id"],
  ["game_plan_week_overrides", "user_id"],
  ["governance_flags", "user_id"],
  ["gp_ab_swing_analyses", "user_id"],
  ["gp_at_bats", "user_id"],
  ["gp_baserun_events", "user_id"],
  ["gp_defense_plays", "user_id"],
  ["gp_documents", "user_id"],
  ["gp_games", "user_id"],
  ["gp_ingest_jobs", "user_id"],
  ["gp_opponent_hitters", "user_id"],
  ["gp_pitcher_dossiers", "user_id"],
  ["gp_pitches", "user_id"],
  ["gp_plan_outcomes", "user_id"],
  ["gp_planner_priors", "user_id"],
  ["gp_pregame_plans", "user_id"],
  ["gp_reports", "user_id"],
  ["gp_subs", "user_id"],
  ["hammer_daily_task_completions", "user_id"],
  ["hammer_state_explanations_v2", "user_id"],
  ["hammer_state_snapshots", "user_id"],
  ["heat_map_snapshots", "user_id"],
  ["hie_dirty_users", "user_id"],
  ["hie_execution_locks", "user_id"],
  ["hie_snapshots", "user_id"],
  ["hydration_logs", "user_id"],
  ["hydration_settings", "user_id"],
  ["iq_user_attempts", "user_id"],
  ["iq_user_concept_mastery", "user_id"],
  ["iq_user_progress", "user_id"],
  ["library_video_analytics", "user_id"],
  ["library_video_likes", "user_id"],
  ["library_video_saves", "user_id"],
  ["meal_templates", "user_id"],
  ["mental_health_journal", "user_id"],
  ["mind_fuel_challenges", "user_id"],
  ["mind_fuel_daily_tasks", "user_id"],
  ["mind_fuel_education_progress", "user_id"],
  ["mind_fuel_streaks", "user_id"],
  ["mindfulness_sessions", "user_id"],
  ["minor_guardian_notifications", "user_id"],
  ["monthly_reports", "user_id"],
  ["mpi_scores", "user_id"],
  ["notification_acks", "user_id"],
  ["notification_preferences", "user_id"],
  ["nutrition_meal_templates", "user_id"],
  ["nutrition_recipes", "user_id"],
  ["nutrition_streaks", "user_id"],
  ["nutrition_suggestion_interactions", "user_id"],
  ["organization_members", "user_id"],
  ["parent_athlete_links", "athlete_user_id"],
  ["parent_athlete_links", "parent_user_id"],
  ["parent_invite_dispatches", "athlete_id"],
  ["performance_sessions", "coach_id"],
  ["performance_sessions", "user_id"],
  ["performance_sessions_ledger", "user_id"],
  ["physio_adult_tracking", "user_id"],
  ["physio_daily_reports", "user_id"],
  ["physio_health_profiles", "user_id"],
  ["player_notes", "player_id"],
  ["recall_messages", "user_id"],
  ["recall_threads", "user_id"],
  ["recruiter_contacts", "user_id"],
  ["royal_timing_sessions", "user_id"],
  ["running_presets", "user_id"],
  ["running_sessions", "user_id"],
  ["safeguarding_notifications", "athlete_id"],
  ["scheduled_practice_sessions", "coach_id"],
  ["scheduled_practice_sessions", "user_id"],
  ["scout_applications", "user_id"],
  ["scout_context", "user_id"],
  ["scout_follows", "player_id"],
  ["scout_follows", "scout_id"],
  ["scout_video_reviews", "player_id"],
  ["scout_video_reviews", "scout_id"],
  ["self_grade_goals", "user_id"],
  ["session_insights", "user_id"],
  ["session_start_moods", "user_id"],
  ["session_videos", "user_id"],
  ["shared_activity_templates", "user_id"],
  ["shopping_lists", "user_id"],
  ["speed_goals", "user_id"],
  ["speed_partner_timings", "user_id"],
  ["speed_sessions", "user_id"],
  ["sprint_analyses", "user_id"],
  ["standard_matches", "athlete_user_id"],
  ["stress_assessments", "user_id"],
  ["sub_module_progress", "user_id"],
  ["tex_vision_adaptive_difficulty", "user_id"],
  ["tex_vision_daily_checklist", "user_id"],
  ["tex_vision_daily_drill_selection", "user_id"],
  ["tex_vision_drill_results", "user_id"],
  ["tex_vision_metrics", "user_id"],
  ["tex_vision_personal_bests", "user_id"],
  ["tex_vision_progress", "user_id"],
  ["tex_vision_s2_diagnostics", "user_id"],
  ["tex_vision_sessions", "user_id"],
  ["tex_vision_unlocks", "user_id"],
  ["thought_logs", "user_id"],
  ["throwing_reps", "user_id"],
  ["timeline_schedule_templates", "user_id"],
  ["training_blocks", "user_id"],
  ["training_preferences", "user_id"],
  ["udl_audit_log", "user_id"],
  ["udl_daily_plans", "user_id"],
  ["udl_drill_completions", "user_id"],
  ["user_behavior_patterns", "user_id"],
  ["user_build_access", "user_id"],
  ["user_consistency_snapshots", "user_id"],
  ["user_day_state_overrides", "user_id"],
  ["user_engine_profile", "user_id"],
  ["user_food_history", "user_id"],
  ["user_injury_progress", "user_id"],
  ["user_nn_suggestions", "user_id"],
  ["user_progress", "user_id"],
  ["user_report_cycles", "user_id"],
  ["user_rest_day_overrides", "user_id"],
  ["user_rest_day_rules", "user_id"],
  ["user_viewed_lessons", "user_id"],
  ["user_viewed_tips", "user_id"],
  ["vault_entries", "user_id"],
  ["vault_favorite_meals", "user_id"],
  ["vault_focus_quizzes", "user_id"],
  ["vault_free_notes", "user_id"],
  ["vault_meal_plans", "user_id"],
  ["vault_nutrition_goals", "user_id"],
  ["vault_nutrition_logs", "user_id"],
  ["vault_performance_tests", "user_id"],
  ["vault_progress_photos", "user_id"],
  ["vault_recaps", "user_id"],
  ["vault_saved_drills", "user_id"],
  ["vault_saved_tips", "user_id"],
  ["vault_scout_grades", "evaluator_id"],
  ["vault_scout_grades", "user_id"],
  ["vault_streaks", "user_id"],
  ["vault_supplement_tracking", "user_id"],
  ["vault_vitamin_logs", "user_id"],
  ["vault_weekly_wellness_quiz", "user_id"],
  ["vault_wellness_goals", "user_id"],
  ["vault_workout_notes", "user_id"],
  ["verified_stat_profiles", "user_id"],
  ["video_annotations", "player_id"],
  ["video_annotations", "scout_id"],
  ["video_notes", "user_id"],
  ["video_user_outcomes", "user_id"],
  ["videos", "user_id"],
  ["weakness_scores", "user_id"],
  ["wearable_metrics", "user_id"],
  ["weather_favorite_locations", "user_id"],
  ["weight_entries", "user_id"],
  ["wellness_milestones", "user_id"],
  ["wellness_preferences", "user_id"],
  ["wk_cns_ledger", "user_id"],
  ["wk_fault_signals", "user_id"],
  ["wk_generation_diagnostics", "user_id"],
  ["wk_movement_overrides", "user_id"],
  ["wk_prescriptions", "user_id"],
  ["wk_recovery_acks", "user_id"],
  ["wk_schedule_overrides", "user_id"],
  ["wk_session_logs", "user_id"],
  ["wk_standard_attempts", "user_id"],
  ["wk_standard_awards", "user_id"],
  ["workout_blocks", "user_id"],
  ["workout_presets", "user_id"],
  // Deleted last (ownership rows / identity rows)
  ["subscriptions", "user_id"],
  ["user_roles", "user_id"],
];

/**
 * Shared library content authored by the user. The content stays for everyone
 * else; only the authorship pointer is cleared.
 */
export const AUTHORSHIP_TABLES: Array<[table: string, column: string]> = [
  ["bundle_discount_codes", "created_by"],
  ["drills", "created_by"],
  ["drill_definitions_versions", "created_by"],
  ["iq_alignment_combos", "created_by"],
  ["iq_situations", "owner_id"],
  ["nutrition_food_database", "created_by"],
  ["udl_constraint_overrides", "created_by"],
  ["video_tag_rules", "created_by"],
  ["video_tag_taxonomy", "created_by"],
];

/** Storage buckets where objects are stored under a `<user_id>/` prefix. */
export const USER_STORAGE_BUCKETS = [
  "videos",
  "avatars",
  "vault-photos",
  "scout-videos",
  "scout-letters",
  "gp-documents",
  "gp-dossier-videos",
];
