#!/usr/bin/env bash
# Regenerates the edge-runtime bundle of the hitting pose tiles. Run after any tile change.
set -euo pipefail
bun build src/lib/biomech/server/poseTileServerEntry.ts --target=browser --format=esm --outfile=supabase/functions/_shared/poseTiles.bundle.js
sed -i '1i // GENERATED by scripts/build-pose-tile-bundle.sh from src/lib/biomech — do not edit.\n// @ts-nocheck' supabase/functions/_shared/poseTiles.bundle.js
