#!/usr/bin/env bash
# Bundles the doctrine documents verbatim into one TS module (no hand-copying).
# Usage: scripts/build-doctrine-bundle.sh <output.ts>
# A missing document is bundled as an empty string so its analysis gets no
# doctrine rather than a guess.
set -euo pipefail
out="${1:?output path required}"
python3 - "$out" <<'PY'
import json, os, sys
src = {
  "hitting": "docs/HITTING-PHILOSOPHY.md",
  "softball_pitching": "docs/SOFTBALL-PITCHING-DOCTRINE.md",
  "throwing": "docs/THROWING-DOCTRINE.md",
  "throwing_research": "docs/THROWING-INJURY-RESEARCH.md",
  "baseball_pitching": "docs/BASEBALL-PITCHING-DOCTRINE.md",
}
lines = ["// GENERATED by scripts/build-doctrine-bundle.sh — do not edit.", "export const DOCTRINE = {"]
for k, p in src.items():
    t = open(p).read() if os.path.exists(p) else ""
    lines.append(f"  {k}: {json.dumps(t)},")
lines.append("} as const;")
open(sys.argv[1], "w").write("\n".join(lines) + "\n")
PY
