-- Pitcher & recovery conditioning rows (owner-authorised live 2026-10-05).
-- Basis per row in evidence_note. Video slot (demo_video_url) left empty for the owner.
-- Instructions live in src/lib/hammer/prescription/movementGuide.ts under the same slugs.
INSERT INTO public.wk_movement_catalog
 (slug,name,category,sport_scope,cue,why_prescribed,cns_cost,default_sets,default_reps,default_duration_seconds,
  family,intensity_class,source_philosophy,evidence_note,movement_pattern,primary_adaptation,season_eligibility,
  equipment,joint_stress,volume_cost,bias,duplicate_group,recovery_window_hours,wic_metadata_complete,
  game_day_legal,practice_day_legal,conditioning_category,energy_system,min_age_years,is_active)
VALUES
 -- Baseball pitcher primers (pitcher_specific, baseball only)
 ('pc_pretension_hold_bb','Tall Pre-Tension Hold','conditioning','baseball','Long and loaded.','Wakes up the long lines from foot to fingers before you pitch.',1,2,1,20,'conditioning','supplemental','Hammers method','OWNER (fascia-first order, addendum C4); shape PROPOSED','isometric','conditioning_repeat_explosive','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',1,1,'mixed','conditioning',12,true,true,true,'pitcher_specific','alactic',0,true),
 ('pc_ankle_pogos_bb','Pitcher Ankle Pogos','conditioning','baseball','Hot floor.','Short, springy contacts so your legs feel quick, not tired.',1,2,15,null,'conditioning','supplemental','Hammers method','OWNER (elastic tier U1); SOURCED Flanagan & Comyns 2008','plyometric','conditioning_repeat_explosive','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',2,1,'mixed','conditioning',24,true,false,true,'pitcher_specific','alactic',0,true),
 ('pc_buildup_strides_bb','Pitcher Build-Up Strides','conditioning','baseball','Smooth gets fast.','A few relaxed fast runs leave you sharp without spending your legs.',1,3,1,null,'conditioning','supplemental','Hammers method','SOURCED Rhea et al. 2008 (short fast work over long running for pitchers); dose PROPOSED','sprint','conditioning_repeat_explosive','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{field}',2,1,'mixed','conditioning',24,true,false,true,'pitcher_specific','alactic',0,true),
 ('rp_ready_series_bb','Reliever Ready Series','conditioning','baseball','Ready, not spent.','Keeps you switched on for a call without using up what you need on the mound.',1,2,1,60,'conditioning','supplemental','Hammers method','OWNER (fascia-first order, elastic over volume); shape and dose PROPOSED','plyometric','conditioning_repeat_explosive','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',1,1,'mixed','conditioning',12,true,true,true,'pitcher_specific','alactic',0,true),
 -- Softball windmill primers (pitcher_specific, softball only) — from SOFTBALL-PITCHING-DOCTRINE.md
 ('sp_drive_bounds_sb','Windmill Drive-Leg Bounds','conditioning','softball','Push the ground away.','Primes the big push off your drive leg that starts every pitch.',1,2,5,null,'conditioning','supplemental','Hammers method','OWNER doctrine (stride_triple_extension, Friesen 1E); SOURCED Oliver et al. 2011 (glute drive in the windmill); dose PROPOSED','plyometric','conditioning_repeat_explosive','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',2,1,'mixed','conditioning',24,true,false,true,'pitcher_specific','alactic',0,true),
 ('sp_stride_stick_sb','Windmill Stride and Stick','conditioning','softball','Land and own it.','Gets your landing leg strong and steady so every pitch lands the same.',1,2,4,null,'conditioning','supplemental','Hammers method','OWNER doctrine (stride knee alignment safety flag, sfc_knee_ankle); SOURCED knee-valgus injury association cited in doctrine; dose PROPOSED','plyometric','conditioning_repeat_explosive','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',2,1,'mixed','conditioning',24,true,false,true,'pitcher_specific','alactic',0,true),
 ('sp_arm_circle_rhythm_sb','Windmill Circle Rhythm','conditioning','softball','Loose circle, fast finish.','Warms the full arm circle the way your body likes to move it.',1,2,8,null,'conditioning','supplemental','Hammers method','OWNER doctrine (windmill circle, not an arc; no universal shape); SOURCED Werner et al. 2006 (windmill shoulder demand); dose PROPOSED','rotation','conditioning_repeat_explosive','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',1,1,'mixed','conditioning',12,true,true,true,'pitcher_specific','alactic',0,true),
 ('rp_ready_series_sb','Windmill Reliever Ready Series','conditioning','softball','Ready, not spent.','Keeps you switched on for a call without using up what you need in the circle.',1,2,1,60,'conditioning','supplemental','Hammers method','OWNER (fascia-first, elastic over volume) + windmill doctrine; shape and dose PROPOSED','plyometric','conditioning_repeat_explosive','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',1,1,'mixed','conditioning',12,true,true,true,'pitcher_specific','alactic',0,true),
 -- Recovery flush (recovery_flush, both sports — not sport-specific movement)
 ('rc_easy_flush','Easy Flush (Bike or Walk)','conditioning','both','Easy enough to chat.','Gets blood moving and loosens you up without adding work.',0,1,1,540,'conditioning','supplemental','Hammers method','SOURCED Dupuy et al. 2018 (active recovery); dose PROPOSED','locomotion','recovery_only','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',1,1,'mixed','conditioning',0,true,true,true,'recovery_flush','aerobic',0,true),
 ('rc_long_reach_walk','Long Reach Walk','conditioning','both','Long from foot to fingers.','Easy whole-body length after a hard day.',0,2,10,null,'conditioning','supplemental','Hammers method','OWNER (whole-chain); shape PROPOSED','locomotion','recovery_only','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',1,1,'mixed','conditioning',0,true,true,true,'recovery_flush','aerobic',0,true),
 ('rc_breathing_reset','Slow Breathing Reset','conditioning','both','Long breath out.','Settles you down so your body can switch off.',0,1,1,120,'conditioning','supplemental','Hammers method','PROPOSED (no medical claim)','breathing','recovery_only','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',1,1,'mixed','conditioning',0,true,true,true,'recovery_flush','aerobic',0,true),
 ('rc_postgame_flush','Same-Night Game Flush','conditioning','both','Walk it off, breathe it down.','A short easy cool-down the night of a game.',0,1,1,480,'conditioning','supplemental','Hammers method','SOURCED Dupuy et al. 2018 (active recovery); shape PROPOSED; no ice','locomotion','recovery_only','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',1,1,'mixed','conditioning',0,true,true,true,'recovery_flush','aerobic',0,true),
 ('rc_travel_reset','Travel-Day Reset','conditioning','both','Get up and move.','Undoes the stiffness of a long trip with easy walking and length.',0,1,1,480,'conditioning','supplemental','Hammers method','OWNER (whole-chain); SOURCED Dupuy et al. 2018 (light activity); shape PROPOSED','locomotion','recovery_only','{os_q1,os_q2,os_q3,os_q4,pre_season,in_season,post_season}','{}',1,1,'mixed','conditioning',0,true,true,true,'recovery_flush','aerobic',0,true)
ON CONFLICT (slug) DO NOTHING;
