-- Create nutrition_daily_tips table
CREATE TABLE public.nutrition_daily_tips (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  category TEXT NOT NULL,
  tip_text TEXT NOT NULL,
  sport TEXT DEFAULT 'both',
  is_ai_generated BOOLEAN DEFAULT false,
  generated_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create user_viewed_tips table
CREATE TABLE public.user_viewed_tips (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  tip_id UUID NOT NULL REFERENCES public.nutrition_daily_tips(id) ON DELETE CASCADE,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, tip_id)
);

-- Enable RLS
ALTER TABLE public.nutrition_daily_tips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_viewed_tips ENABLE ROW LEVEL SECURITY;

-- RLS policies for nutrition_daily_tips (readable by all authenticated users)
CREATE POLICY "Authenticated users can view tips" ON public.nutrition_daily_tips
  FOR SELECT USING (auth.uid() IS NOT NULL);

-- RLS policies for user_viewed_tips
CREATE POLICY "Users can view their own viewed tips" ON public.user_viewed_tips
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own viewed tips" ON public.user_viewed_tips
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Service role can insert AI-generated tips
CREATE POLICY "Service role can insert tips" ON public.nutrition_daily_tips
  FOR INSERT WITH CHECK (true);

-- Indexes for performance
CREATE INDEX idx_nutrition_tips_category ON public.nutrition_daily_tips(category);
CREATE INDEX idx_nutrition_tips_sport ON public.nutrition_daily_tips(sport);
CREATE INDEX idx_user_viewed_tips_user ON public.user_viewed_tips(user_id);

-- Seed 515+ tips across all 18 categories
INSERT INTO public.nutrition_daily_tips (category, tip_text, sport) VALUES
-- Blood Type Health (30 tips)
('blood_type', 'Type A athletes often thrive on plant-based proteins like lentils, beans, and tofu for optimal digestion.', 'both'),
('blood_type', 'Type O athletes typically perform well with lean proteins like chicken, fish, and grass-fed beef.', 'both'),
('blood_type', 'Type B athletes may benefit from a varied diet including dairy, eggs, and green vegetables.', 'both'),
('blood_type', 'Type AB athletes often do well with a mix of seafood, tofu, dairy, and green vegetables.', 'both'),
('blood_type', 'Type A individuals may want to limit red meat consumption and focus on fish and poultry.', 'both'),
('blood_type', 'Type O athletes might consider avoiding wheat and dairy if experiencing digestive issues.', 'both'),
('blood_type', 'Type B individuals often tolerate dairy better than other blood types.', 'both'),
('blood_type', 'Type AB athletes may benefit from smaller, more frequent meals throughout the day.', 'both'),
('blood_type', 'Type A athletes often respond well to calming exercises like yoga combined with their nutrition plan.', 'both'),
('blood_type', 'Type O individuals typically have higher stomach acid, aiding protein digestion.', 'both'),
('blood_type', 'All blood types benefit from eating whole, unprocessed foods as the foundation of their diet.', 'both'),
('blood_type', 'Type A athletes may find green tea more beneficial than coffee for energy.', 'both'),
('blood_type', 'Type B individuals often do well with lamb, goat, and rabbit as protein sources.', 'both'),
('blood_type', 'Type AB athletes might benefit from avoiding smoked or cured meats.', 'both'),
('blood_type', 'Type O athletes often perform better when limiting grain consumption.', 'both'),
('blood_type', 'Type A individuals may benefit from fermented foods like miso and sauerkraut.', 'both'),
('blood_type', 'Type B athletes often tolerate eggs well as a protein source.', 'both'),
('blood_type', 'Type AB individuals may want to avoid corn, buckwheat, and kidney beans.', 'both'),
('blood_type', 'Type O athletes typically thrive on high-protein, low-carb eating patterns.', 'both'),
('blood_type', 'Type A athletes often benefit from avoiding tomatoes and potatoes.', 'both'),
('blood_type', 'Type B individuals may want to limit chicken consumption and choose turkey instead.', 'both'),
('blood_type', 'Type AB athletes often do well with rice as their primary grain.', 'both'),
('blood_type', 'Type O individuals may benefit from kelp and seafood for thyroid support.', 'both'),
('blood_type', 'Type A athletes often respond well to gentle cardiovascular exercise after meals.', 'both'),
('blood_type', 'Type B athletes may benefit from moderate dairy consumption for calcium.', 'both'),
('blood_type', 'Type AB individuals often thrive on a Mediterranean-style eating pattern.', 'both'),
('blood_type', 'Type O athletes may want to avoid pork and processed meats.', 'both'),
('blood_type', 'Type A individuals often benefit from olive oil as their primary fat source.', 'both'),
('blood_type', 'Type B athletes may do well with oatmeal as a pre-game breakfast option.', 'both'),
('blood_type', 'Type AB athletes often benefit from walnuts and peanuts as snack options.', 'both'),

-- Hydration (35 tips)
('hydration', 'Drink 16-20 oz of water 2-3 hours before practice or games to ensure proper hydration.', 'both'),
('hydration', 'During activity, aim for 7-10 oz of fluid every 10-20 minutes.', 'both'),
('hydration', 'Monitor urine color - pale yellow indicates good hydration, dark yellow means drink more.', 'both'),
('hydration', 'Add a pinch of sea salt to water during hot weather to replace lost electrolytes.', 'both'),
('hydration', 'Coconut water is a natural electrolyte drink with potassium and magnesium.', 'both'),
('hydration', 'Avoid sugary sports drinks unless exercising intensely for over 60 minutes.', 'both'),
('hydration', 'Cold water absorbs faster than room temperature water during exercise.', 'both'),
('hydration', 'Weigh yourself before and after practice - drink 16-24 oz for every pound lost.', 'both'),
('hydration', 'Caffeine in moderation does not cause dehydration despite common myths.', 'both'),
('hydration', 'Watermelon is 92% water and provides natural hydration plus vitamins.', 'both'),
('hydration', 'Cucumbers, celery, and lettuce are excellent hydrating food choices.', 'both'),
('hydration', 'Avoid alcohol the night before games as it significantly impairs hydration.', 'both'),
('hydration', 'Herbal teas count toward daily fluid intake and provide antioxidants.', 'both'),
('hydration', 'Set phone reminders to drink water if you struggle to stay hydrated.', 'both'),
('hydration', 'Milk provides hydration plus protein and carbs for recovery.', 'both'),
('hydration', 'Oral rehydration solutions work faster than plain water for severe dehydration.', 'both'),
('hydration', 'Sparkling water hydrates just as effectively as still water.', 'both'),
('hydration', 'Sodium helps your body retain fluid - dont fear salt during hot weather training.', 'both'),
('hydration', 'Drink water with meals to aid digestion and nutrient absorption.', 'both'),
('hydration', 'Fruits like oranges, grapes, and berries contribute to daily hydration needs.', 'both'),
('hydration', 'Dehydration of just 2% body weight can decrease performance by 10-20%.', 'both'),
('hydration', 'Start hydrating the day before a big game, not just game day morning.', 'both'),
('hydration', 'Bone broth provides hydration plus collagen and minerals for joint health.', 'both'),
('hydration', 'Avoid energy drinks as primary hydration - they often cause more harm than good.', 'both'),
('hydration', 'Room temperature water is easier to drink in larger quantities than ice cold.', 'both'),
('hydration', 'Pitchers should drink water between every inning to maintain performance.', 'baseball'),
('hydration', 'Catchers lose significant fluid in gear - prioritize hydration between innings.', 'baseball'),
('hydration', 'Softball pitchers should hydrate before and after each at-bat they face.', 'softball'),
('hydration', 'Keep a water bottle in the dugout and take sips every half inning.', 'both'),
('hydration', 'Humid conditions require even more fluid intake than dry heat.', 'both'),
('hydration', 'Electrolyte tablets are a convenient way to enhance water during long tournaments.', 'both'),
('hydration', 'Avoid drinking large amounts at once - small sips throughout are more effective.', 'both'),
('hydration', 'Frozen fruit smoothies provide hydration, nutrients, and cooling benefits.', 'both'),
('hydration', 'Soup and broth count toward daily fluid intake and provide sodium.', 'both'),
('hydration', 'A good goal is half your body weight in ounces of water daily, more during activity.', 'both'),

-- Minerals (30 tips)
('minerals', 'Magnesium supports muscle function - find it in nuts, seeds, and dark chocolate.', 'both'),
('minerals', 'Iron carries oxygen to muscles - athletes need more than sedentary individuals.', 'both'),
('minerals', 'Zinc supports immune function and wound healing - oysters are the richest source.', 'both'),
('minerals', 'Calcium from dairy, leafy greens, and fortified foods supports bone strength.', 'both'),
('minerals', 'Potassium from bananas, potatoes, and avocados prevents muscle cramps.', 'both'),
('minerals', 'Selenium in Brazil nuts supports thyroid function and immune health.', 'both'),
('minerals', 'Copper from shellfish and nuts supports iron absorption and energy production.', 'both'),
('minerals', 'Manganese in whole grains supports bone health and metabolism.', 'both'),
('minerals', 'Phosphorus in meat, dairy, and fish works with calcium for strong bones.', 'both'),
('minerals', 'Chromium in broccoli and whole grains helps regulate blood sugar.', 'both'),
('minerals', 'Female athletes are at higher risk for iron deficiency - get levels checked regularly.', 'both'),
('minerals', 'Vitamin C enhances iron absorption - pair iron-rich foods with citrus.', 'both'),
('minerals', 'Spinach contains iron but also oxalates that reduce absorption - cook it to improve.', 'both'),
('minerals', 'Red meat is the most bioavailable source of iron for athletes.', 'both'),
('minerals', 'Pumpkin seeds are an excellent source of magnesium and zinc.', 'both'),
('minerals', 'Himalayan pink salt contains trace minerals not found in table salt.', 'both'),
('minerals', 'Bone-in sardines provide calcium without dairy.', 'both'),
('minerals', 'Sweet potatoes provide potassium, magnesium, and complex carbs.', 'both'),
('minerals', 'Mineral deficiencies can cause fatigue, cramping, and poor recovery.', 'both'),
('minerals', 'Hard training increases mineral loss through sweat - replenish accordingly.', 'both'),
('minerals', 'Iodine from seafood and iodized salt supports thyroid and metabolism.', 'both'),
('minerals', 'Molybdenum in legumes helps detoxify harmful substances.', 'both'),
('minerals', 'Boron in raisins and almonds supports bone and brain health.', 'both'),
('minerals', 'Silicon in oats and bananas supports connective tissue health.', 'both'),
('minerals', 'Sulfur in garlic and onions supports detoxification pathways.', 'both'),
('minerals', 'Mineral water can contribute to daily mineral intake.', 'both'),
('minerals', 'Blackstrap molasses is surprisingly high in iron, calcium, and potassium.', 'both'),
('minerals', 'Cashews provide copper, magnesium, and zinc in one convenient snack.', 'both'),
('minerals', 'Quinoa contains all essential minerals and is a complete protein.', 'both'),
('minerals', 'Hemp seeds provide magnesium, zinc, and iron in small servings.', 'both'),

-- Recovery (35 tips)
('recovery', 'Consume protein within 30-60 minutes after training for optimal muscle repair.', 'both'),
('recovery', 'Tart cherry juice reduces inflammation and muscle soreness after games.', 'both'),
('recovery', 'Sleep is the most important recovery tool - aim for 8-10 hours for athletes.', 'both'),
('recovery', 'Omega-3 fatty acids from fish reduce inflammation and speed recovery.', 'both'),
('recovery', 'Chocolate milk provides an ideal ratio of carbs to protein for recovery.', 'both'),
('recovery', 'Collagen peptides support tendon and ligament recovery after hard training.', 'both'),
('recovery', 'Ginger has natural anti-inflammatory properties to aid recovery.', 'both'),
('recovery', 'Turmeric combined with black pepper reduces muscle inflammation.', 'both'),
('recovery', 'Epsom salt baths provide magnesium absorption through the skin.', 'both'),
('recovery', 'Active recovery like light walking improves blood flow and reduces soreness.', 'both'),
('recovery', 'Foam rolling after games helps flush metabolic waste from muscles.', 'both'),
('recovery', 'Protein before bed supports overnight muscle repair and growth.', 'both'),
('recovery', 'BCAAs during training can reduce muscle breakdown and soreness.', 'both'),
('recovery', 'Adequate carb intake after training restores muscle glycogen.', 'both'),
('recovery', 'Massage increases blood flow and reduces recovery time between games.', 'both'),
('recovery', 'Cold water immersion after games can reduce inflammation and soreness.', 'both'),
('recovery', 'Contrast showers alternating hot and cold improve circulation.', 'both'),
('recovery', 'Pineapple contains bromelain which reduces inflammation naturally.', 'both'),
('recovery', 'Beetroot juice improves blood flow and may speed recovery.', 'both'),
('recovery', 'Adequate sleep allows growth hormone release for tissue repair.', 'both'),
('recovery', 'Stress management is crucial - cortisol impairs recovery significantly.', 'both'),
('recovery', 'Avoid alcohol after games - it significantly impairs muscle recovery.', 'both'),
('recovery', 'Watermelon contains L-citrulline which reduces muscle soreness.', 'both'),
('recovery', 'Greek yogurt provides protein and probiotics for gut-supported recovery.', 'both'),
('recovery', 'Compression garments may improve blood flow and reduce swelling.', 'both'),
('recovery', 'After pitching, focus on anti-inflammatory foods for arm recovery.', 'baseball'),
('recovery', 'Post-game protein shakes are convenient when appetite is low.', 'both'),
('recovery', 'Catchers should prioritize knee and hip recovery with targeted nutrition.', 'baseball'),
('recovery', 'Bone broth provides collagen and minerals for joint recovery.', 'both'),
('recovery', 'Stretching combined with proper nutrition optimizes flexibility recovery.', 'both'),
('recovery', 'Hydration continues to be important post-game for nutrient transport.', 'both'),
('recovery', 'Cottage cheese before bed provides slow-digesting casein protein.', 'both'),
('recovery', 'Antioxidants from berries help neutralize exercise-induced free radicals.', 'both'),
('recovery', 'Potassium-rich foods help restore electrolyte balance after sweating.', 'both'),
('recovery', 'Rest days are when adaptation happens - fuel them properly too.', 'both'),

-- Blood Flow (25 tips)
('blood_flow', 'Nitric oxide from beets improves blood flow and oxygen delivery to muscles.', 'both'),
('blood_flow', 'Dark chocolate improves blood vessel function and circulation.', 'both'),
('blood_flow', 'Garlic supports healthy blood pressure and improves circulation.', 'both'),
('blood_flow', 'Cayenne pepper stimulates blood flow throughout the body.', 'both'),
('blood_flow', 'Pomegranate juice supports artery health and blood flow.', 'both'),
('blood_flow', 'Citrus fruits improve blood vessel flexibility and function.', 'both'),
('blood_flow', 'Fatty fish like salmon improve blood flow and reduce inflammation.', 'both'),
('blood_flow', 'Walnuts support blood vessel health with omega-3s and L-arginine.', 'both'),
('blood_flow', 'Tomatoes contain lycopene which supports cardiovascular health.', 'both'),
('blood_flow', 'Berries improve blood vessel function and reduce blood pressure.', 'both'),
('blood_flow', 'Leafy greens are high in nitrates that convert to nitric oxide.', 'both'),
('blood_flow', 'Onions contain quercetin which supports blood vessel health.', 'both'),
('blood_flow', 'Cinnamon improves blood vessel dilation and circulation.', 'both'),
('blood_flow', 'Green tea improves blood vessel function and circulation.', 'both'),
('blood_flow', 'Avoid trans fats which damage blood vessels and impair flow.', 'both'),
('blood_flow', 'Regular movement prevents blood pooling and maintains circulation.', 'both'),
('blood_flow', 'Proper warm-ups increase blood flow to working muscles before activity.', 'both'),
('blood_flow', 'Compression socks can improve blood flow during travel to games.', 'both'),
('blood_flow', 'Deep breathing exercises improve oxygenation and blood flow.', 'both'),
('blood_flow', 'Ginkgo biloba may support cerebral blood flow and mental clarity.', 'both'),
('blood_flow', 'Vitamin E from almonds and sunflower seeds supports blood vessel health.', 'both'),
('blood_flow', 'Ginger improves circulation and has anti-clotting properties.', 'both'),
('blood_flow', 'Adequate hydration maintains blood volume for optimal circulation.', 'both'),
('blood_flow', 'Iron supports oxygen-carrying capacity of red blood cells.', 'both'),
('blood_flow', 'Avoid smoking and secondhand smoke which severely impairs blood flow.', 'both'),

-- Lymphatic Health (25 tips)
('lymphatic', 'The lymphatic system removes waste - movement is essential for lymph flow.', 'both'),
('lymphatic', 'Dry brushing before showers stimulates lymphatic circulation.', 'both'),
('lymphatic', 'Rebounding or jumping rope activates the lymphatic system effectively.', 'both'),
('lymphatic', 'Deep breathing creates pressure changes that move lymph fluid.', 'both'),
('lymphatic', 'Massage therapy helps move lymph fluid and reduce congestion.', 'both'),
('lymphatic', 'Adequate water intake is essential for lymphatic fluid movement.', 'both'),
('lymphatic', 'Citrus fruits support lymphatic cleansing and detoxification.', 'both'),
('lymphatic', 'Leafy greens provide chlorophyll which supports lymphatic health.', 'both'),
('lymphatic', 'Avoid tight clothing that restricts lymphatic flow.', 'both'),
('lymphatic', 'Echinacea may support lymphatic immune function.', 'both'),
('lymphatic', 'Contrast showers stimulate lymphatic circulation.', 'both'),
('lymphatic', 'Reduce processed foods which can congest the lymphatic system.', 'both'),
('lymphatic', 'Yoga poses with inversions help drain lymph toward the heart.', 'both'),
('lymphatic', 'Astragalus herb supports lymphatic and immune function.', 'both'),
('lymphatic', 'Walking is one of the best exercises for lymphatic movement.', 'both'),
('lymphatic', 'Red clover tea traditionally supports lymphatic cleansing.', 'both'),
('lymphatic', 'Cranberries support lymphatic health and urinary function.', 'both'),
('lymphatic', 'Reduce salt intake to prevent lymphatic congestion and swelling.', 'both'),
('lymphatic', 'Adequate protein intake supports lymphatic tissue health.', 'both'),
('lymphatic', 'Ginger stimulates lymphatic circulation and reduces inflammation.', 'both'),
('lymphatic', 'Dandelion root supports lymphatic drainage and liver function.', 'both'),
('lymphatic', 'Foam rolling can help stimulate superficial lymphatic flow.', 'both'),
('lymphatic', 'Avoid sitting for long periods which impairs lymph circulation.', 'both'),
('lymphatic', 'Cleavers herb is traditionally used to support lymphatic health.', 'both'),
('lymphatic', 'Seaweed contains iodine which supports lymphatic function.', 'both'),

-- Vitamins (35 tips)
('vitamins', 'Vitamin D from sunlight and supplements supports bone health and immune function.', 'both'),
('vitamins', 'Vitamin C from citrus fruits supports collagen production and immune health.', 'both'),
('vitamins', 'B vitamins from whole grains support energy production and metabolism.', 'both'),
('vitamins', 'Vitamin A from sweet potatoes and carrots supports vision and immune function.', 'both'),
('vitamins', 'Vitamin E from nuts and seeds protects cells from oxidative damage.', 'both'),
('vitamins', 'Vitamin K from leafy greens supports blood clotting and bone health.', 'both'),
('vitamins', 'B12 from animal products supports nerve function and red blood cell production.', 'both'),
('vitamins', 'Folate from leafy greens supports cell division and DNA synthesis.', 'both'),
('vitamins', 'Biotin from eggs supports hair, skin, and nail health.', 'both'),
('vitamins', 'Niacin from chicken and fish supports energy metabolism.', 'both'),
('vitamins', 'Riboflavin from dairy supports energy production and antioxidant function.', 'both'),
('vitamins', 'Thiamine from whole grains supports carbohydrate metabolism.', 'both'),
('vitamins', 'Pantothenic acid from avocados supports hormone and energy production.', 'both'),
('vitamins', 'Vitamin B6 from bananas supports protein metabolism and brain function.', 'both'),
('vitamins', 'Athletes may need higher vitamin D levels - consider testing your levels.', 'both'),
('vitamins', 'Vitamin C is water-soluble - consume it daily as the body doesnt store it.', 'both'),
('vitamins', 'Fat-soluble vitamins A, D, E, K are best absorbed with dietary fat.', 'both'),
('vitamins', 'Multivitamins can fill gaps but shouldnt replace whole food nutrition.', 'both'),
('vitamins', 'Vitamin D deficiency is common in athletes who train indoors.', 'both'),
('vitamins', 'B vitamins work together - deficiency in one can affect others.', 'both'),
('vitamins', 'Cooking can destroy some vitamins - include raw fruits and vegetables.', 'both'),
('vitamins', 'Vitamin C enhances iron absorption from plant-based sources.', 'both'),
('vitamins', 'Vitamin E may help reduce exercise-induced oxidative stress.', 'both'),
('vitamins', 'Athletes need more B vitamins due to increased energy demands.', 'both'),
('vitamins', 'Vitamin A supports night vision - important for evening games.', 'both'),
('vitamins', 'Choline from eggs supports brain function and muscle movement.', 'both'),
('vitamins', 'Vitamin K2 from fermented foods supports calcium metabolism.', 'both'),
('vitamins', 'Excessive vitamin supplementation can be harmful - more isnt always better.', 'both'),
('vitamins', 'Vitamin D supports muscle function and may improve athletic performance.', 'both'),
('vitamins', 'B12 supplementation may be necessary for vegetarian and vegan athletes.', 'both'),
('vitamins', 'Vitamin C supports adrenal function during high-stress training periods.', 'both'),
('vitamins', 'Beta-carotene from orange vegetables converts to vitamin A as needed.', 'both'),
('vitamins', 'Inositol supports cell membrane health and may reduce anxiety.', 'both'),
('vitamins', 'PABA supports skin health and protection from sun exposure.', 'both'),
('vitamins', 'Vitamin supplements are best taken with food for optimal absorption.', 'both'),

-- Daily Nutrition (35 tips)
('daily_nutrition', 'Eat breakfast within an hour of waking to kickstart metabolism.', 'both'),
('daily_nutrition', 'Include protein at every meal to support muscle maintenance.', 'both'),
('daily_nutrition', 'Fill half your plate with vegetables at lunch and dinner.', 'both'),
('daily_nutrition', 'Eat the rainbow - different colored foods provide different nutrients.', 'both'),
('daily_nutrition', 'Plan meals ahead to avoid poor food choices when hungry.', 'both'),
('daily_nutrition', 'Meal prep on weekends to ensure healthy options are available.', 'both'),
('daily_nutrition', 'Keep healthy snacks readily available to avoid junk food temptation.', 'both'),
('daily_nutrition', 'Eat mindfully - slow down and chew food thoroughly for better digestion.', 'both'),
('daily_nutrition', 'Dont skip meals - consistent eating supports stable energy levels.', 'both'),
('daily_nutrition', 'Read nutrition labels to make informed food choices.', 'both'),
('daily_nutrition', 'Choose whole grains over refined grains for sustained energy.', 'both'),
('daily_nutrition', 'Include healthy fats like avocado, nuts, and olive oil daily.', 'both'),
('daily_nutrition', 'Limit added sugars to less than 10% of daily calories.', 'both'),
('daily_nutrition', 'Eat fermented foods like yogurt and kimchi for gut health.', 'both'),
('daily_nutrition', 'Dont drink your calories - limit sodas and sugary beverages.', 'both'),
('daily_nutrition', 'Cook at home more often to control ingredients and portions.', 'both'),
('daily_nutrition', 'Use herbs and spices instead of salt for flavor and health benefits.', 'both'),
('daily_nutrition', 'Include fiber from vegetables, fruits, and whole grains daily.', 'both'),
('daily_nutrition', 'Stay consistent with eating times to regulate hunger hormones.', 'both'),
('daily_nutrition', 'Balance macronutrients at each meal - protein, carbs, and fats.', 'both'),
('daily_nutrition', 'Limit processed foods and focus on whole, single-ingredient foods.', 'both'),
('daily_nutrition', 'Dont grocery shop when hungry to avoid impulse purchases.', 'both'),
('daily_nutrition', 'Keep a food journal to track eating patterns and identify issues.', 'both'),
('daily_nutrition', 'Practice portion control using your hand as a measuring guide.', 'both'),
('daily_nutrition', 'Include a variety of protein sources - not just meat.', 'both'),
('daily_nutrition', 'Eat slowly to recognize fullness signals before overeating.', 'both'),
('daily_nutrition', 'Pre-game meals should be familiar foods you know you tolerate well.', 'both'),
('daily_nutrition', 'Post-game meals should include protein and carbs for recovery.', 'both'),
('daily_nutrition', 'Snack on fruits and vegetables between meals for sustained energy.', 'both'),
('daily_nutrition', 'Limit caffeine after 2pm to protect sleep quality.', 'both'),
('daily_nutrition', 'Choose lean protein sources most of the time.', 'both'),
('daily_nutrition', 'Include omega-3 rich foods like salmon at least twice weekly.', 'both'),
('daily_nutrition', 'Avoid eating large meals close to bedtime.', 'both'),
('daily_nutrition', 'Use smaller plates to naturally control portion sizes.', 'both'),
('daily_nutrition', 'Make water your primary beverage choice throughout the day.', 'both'),

-- Longevity (25 tips)
('longevity', 'Caloric restriction without malnutrition may support longevity.', 'both'),
('longevity', 'Intermittent fasting may support cellular repair processes.', 'both'),
('longevity', 'Blue zone diets emphasize plants, legumes, and moderate protein.', 'both'),
('longevity', 'Resveratrol from red grapes may activate longevity genes.', 'both'),
('longevity', 'Reducing sugar intake may slow aging at the cellular level.', 'both'),
('longevity', 'Omega-3 fatty acids support brain health throughout life.', 'both'),
('longevity', 'Maintaining muscle mass through protein and exercise extends healthspan.', 'both'),
('longevity', 'Colorful vegetables provide antioxidants that protect against aging.', 'both'),
('longevity', 'Social connections and community meals support mental and physical health.', 'both'),
('longevity', 'Adequate sleep is essential for longevity and cellular repair.', 'both'),
('longevity', 'Green tea contains compounds associated with longer lifespan.', 'both'),
('longevity', 'Turmeric has anti-aging properties and reduces inflammation.', 'both'),
('longevity', 'Maintaining healthy weight reduces risk of age-related diseases.', 'both'),
('longevity', 'Regular physical activity is one of the strongest predictors of longevity.', 'both'),
('longevity', 'Stress management through nutrition and lifestyle supports long-term health.', 'both'),
('longevity', 'Nuts are associated with reduced mortality in multiple studies.', 'both'),
('longevity', 'Olive oil consumption is linked to longevity in Mediterranean populations.', 'both'),
('longevity', 'Limiting alcohol consumption supports liver health and longevity.', 'both'),
('longevity', 'Fiber intake is associated with reduced risk of chronic diseases.', 'both'),
('longevity', 'Vitamin D sufficiency is associated with better health outcomes with aging.', 'both'),
('longevity', 'Maintaining cognitive activity alongside nutrition supports brain longevity.', 'both'),
('longevity', 'Spermidine from wheat germ and aged cheese may support cellular health.', 'both'),
('longevity', 'NAD+ precursors from milk and fish may support energy metabolism.', 'both'),
('longevity', 'Quercetin from onions and apples has senolytic properties.', 'both'),
('longevity', 'Career longevity in sports requires consistent attention to nutrition.', 'both'),

-- Weight Management (30 tips)
('weight', 'Create a modest caloric deficit of 300-500 calories for sustainable fat loss.', 'both'),
('weight', 'Protein intake of 1g per pound of body weight supports muscle retention during weight loss.', 'both'),
('weight', 'Dont drastically cut calories - it can impair performance and metabolism.', 'both'),
('weight', 'Fiber keeps you full longer - aim for 25-35g daily.', 'both'),
('weight', 'Eat protein first at meals to enhance satiety.', 'both'),
('weight', 'Sleep deprivation increases hunger hormones and cravings.', 'both'),
('weight', 'Stress increases cortisol which can lead to weight gain.', 'both'),
('weight', 'Strength training builds muscle which increases resting metabolic rate.', 'both'),
('weight', 'Track food intake honestly to identify areas for improvement.', 'both'),
('weight', 'Avoid liquid calories which dont provide satiety.', 'both'),
('weight', 'Eat whole foods which are more filling than processed alternatives.', 'both'),
('weight', 'Dont eliminate entire food groups - balance is key.', 'both'),
('weight', 'Scale weight fluctuates daily due to water - track weekly trends instead.', 'both'),
('weight', 'Building muscle is more important for athletes than just losing weight.', 'both'),
('weight', 'Rapid weight loss can impair immune function and recovery.', 'both'),
('weight', 'Focus on body composition, not just scale weight.', 'both'),
('weight', 'Eat regularly to prevent extreme hunger that leads to overeating.', 'both'),
('weight', 'Vegetables are low calorie but high volume - fill up on them.', 'both'),
('weight', 'Avoid all-or-nothing thinking - one bad meal doesnt ruin progress.', 'both'),
('weight', 'Patience is essential - sustainable changes take time.', 'both'),
('weight', 'Dont compare your body to others - focus on your own progress.', 'both'),
('weight', 'In-season is not the time for aggressive weight loss.', 'both'),
('weight', 'Off-season allows for more flexibility in body composition goals.', 'both'),
('weight', 'Consult a sports dietitian for personalized weight management guidance.', 'both'),
('weight', 'Catchers may need more calories due to constant movement behind the plate.', 'baseball'),
('weight', 'Pitchers should maintain weight during season to preserve arm strength.', 'baseball'),
('weight', 'Avoid weight-cutting practices that impair hydration and performance.', 'both'),
('weight', 'Healthy fats help regulate hormones important for weight management.', 'both'),
('weight', 'Mindful eating prevents unconscious overeating.', 'both'),
('weight', 'Small sustainable changes are better than extreme short-term diets.', 'both'),

-- Vegan Guidance (25 tips)
('vegan', 'Combine different plant proteins to get all essential amino acids.', 'both'),
('vegan', 'B12 supplementation is essential for vegan athletes.', 'both'),
('vegan', 'Iron from plant sources is less absorbable - pair with vitamin C.', 'both'),
('vegan', 'Omega-3s from algae supplements provide DHA and EPA without fish.', 'both'),
('vegan', 'Legumes, tofu, tempeh, and seitan are excellent protein sources.', 'both'),
('vegan', 'Fortified plant milks provide calcium and vitamin D.', 'both'),
('vegan', 'Nutritional yeast provides B vitamins and a cheesy flavor.', 'both'),
('vegan', 'Hemp, chia, and flax seeds provide protein and omega-3s.', 'both'),
('vegan', 'Quinoa and buckwheat are complete plant proteins.', 'both'),
('vegan', 'Spirulina and chlorella provide protein and minerals.', 'both'),
('vegan', 'Vegan athletes may need to eat larger volumes to meet calorie needs.', 'both'),
('vegan', 'Zinc from pumpkin seeds and legumes supports immune function.', 'both'),
('vegan', 'Iodine from seaweed or supplements supports thyroid function.', 'both'),
('vegan', 'Calcium-fortified foods help meet daily calcium needs without dairy.', 'both'),
('vegan', 'Plant-based protein powders can help meet protein requirements.', 'both'),
('vegan', 'Vitamin D3 from lichen is a vegan-friendly supplement option.', 'both'),
('vegan', 'Creatine supplementation may benefit vegan athletes more than omnivores.', 'both'),
('vegan', 'Taurine supplementation may support vegan athletes cardiac health.', 'both'),
('vegan', 'Edamame provides complete protein with all essential amino acids.', 'both'),
('vegan', 'Lentils provide iron, protein, and complex carbohydrates.', 'both'),
('vegan', 'Mushrooms exposed to UV light provide vitamin D.', 'both'),
('vegan', 'Fermented soy products like tempeh are more digestible than tofu.', 'both'),
('vegan', 'Vegan athletes should work with a dietitian to ensure adequacy.', 'both'),
('vegan', 'Many successful professional athletes follow plant-based diets.', 'both'),
('vegan', 'Plan meals carefully to ensure adequate protein and calories.', 'both'),

-- Restrictive Diets (25 tips)
('restrictive', 'Gluten-free athletes should choose whole grains like rice and quinoa.', 'both'),
('restrictive', 'Dairy-free calcium sources include fortified milks and leafy greens.', 'both'),
('restrictive', 'Egg allergies can be worked around with chia eggs and flax eggs in baking.', 'both'),
('restrictive', 'Nut-free protein sources include seeds, soy, and animal proteins.', 'both'),
('restrictive', 'FODMAP diets may help athletes with digestive issues.', 'both'),
('restrictive', 'Elimination diets should be supervised by a healthcare professional.', 'both'),
('restrictive', 'Read labels carefully to avoid allergens in unexpected places.', 'both'),
('restrictive', 'Cross-contamination can be an issue - communicate allergies clearly.', 'both'),
('restrictive', 'Travel with safe snacks when dietary restrictions make eating out difficult.', 'both'),
('restrictive', 'Many restaurants now accommodate common dietary restrictions.', 'both'),
('restrictive', 'Celiac athletes must be vigilant about gluten cross-contamination.', 'both'),
('restrictive', 'Lactose intolerance can often tolerate aged cheeses and yogurt.', 'both'),
('restrictive', 'Soy-free athletes can use coconut aminos instead of soy sauce.', 'both'),
('restrictive', 'Corn-free athletes should check medications and supplements.', 'both'),
('restrictive', 'Nightshade-free diets eliminate tomatoes, peppers, and potatoes.', 'both'),
('restrictive', 'Autoimmune protocols may help athletes with chronic inflammation.', 'both'),
('restrictive', 'Histamine intolerance requires avoiding aged and fermented foods.', 'both'),
('restrictive', 'Oxalate-sensitive athletes should limit spinach and almonds.', 'both'),
('restrictive', 'Sulfite sensitivity requires avoiding dried fruits and wine.', 'both'),
('restrictive', 'Salicylate sensitivity may require avoiding many fruits and vegetables.', 'both'),
('restrictive', 'Work with a dietitian to ensure nutritional adequacy on restrictive diets.', 'both'),
('restrictive', 'Dont self-diagnose food intolerances - get proper testing.', 'both'),
('restrictive', 'Some restrictions may be temporary while gut health improves.', 'both'),
('restrictive', 'Communicate dietary needs to team staff and trainers.', 'both'),
('restrictive', 'Plan ahead for team meals and road trips with dietary restrictions.', 'both'),

-- Off-season Body Priming (25 tips)
('offseason', 'Off-season is the best time to address nutritional deficiencies.', 'both'),
('offseason', 'Focus on building lean muscle mass during the off-season.', 'both'),
('offseason', 'Increase protein intake to support off-season strength training.', 'both'),
('offseason', 'Address any digestive issues during the off-season when stress is lower.', 'both'),
('offseason', 'Off-season allows for more dietary experimentation and variety.', 'both'),
('offseason', 'Get comprehensive blood work done during the off-season.', 'both'),
('offseason', 'Focus on gut health with fermented foods and fiber.', 'both'),
('offseason', 'Off-season is ideal for implementing new eating habits.', 'both'),
('offseason', 'Reduce refined sugar intake to improve metabolic health.', 'both'),
('offseason', 'Prioritize sleep and recovery nutrition during off-season training.', 'both'),
('offseason', 'Build a base of aerobic fitness supported by proper nutrition.', 'both'),
('offseason', 'Off-season body composition changes are easier than in-season.', 'both'),
('offseason', 'Experiment with meal timing to find what works best for you.', 'both'),
('offseason', 'Address any chronic inflammation with anti-inflammatory foods.', 'both'),
('offseason', 'Off-season is a good time to try new healthy recipes.', 'both'),
('offseason', 'Work with a dietitian to create a personalized off-season plan.', 'both'),
('offseason', 'Gradually adjust calorie intake as training volume changes.', 'both'),
('offseason', 'Focus on food quality more than strict calorie counting.', 'both'),
('offseason', 'Build healthy habits that will carry into the season.', 'both'),
('offseason', 'Off-season detox from processed foods can reset taste preferences.', 'both'),
('offseason', 'Prepare your body for the demands of spring training.', 'baseball'),
('offseason', 'Use the off-season to heal any lingering injuries with proper nutrition.', 'both'),
('offseason', 'Maintain some structure to avoid excessive off-season weight gain.', 'both'),
('offseason', 'Off-season allows time for longer meal prep and cooking.', 'both'),
('offseason', 'Set nutritional goals for the upcoming season during off-season.', 'both'),

-- In-season Body Priming (25 tips)
('inseason', 'Maintain consistent eating patterns throughout the season.', 'both'),
('inseason', 'Prioritize recovery nutrition after every game and practice.', 'both'),
('inseason', 'Dont try new foods on game day - stick to familiar choices.', 'both'),
('inseason', 'Keep energy intake high enough to support training demands.', 'both'),
('inseason', 'In-season is not the time for restrictive dieting.', 'both'),
('inseason', 'Pack snacks for long bus rides to away games.', 'both'),
('inseason', 'Stay hydrated throughout the season, not just on hot days.', 'both'),
('inseason', 'Prioritize sleep nutrition with tart cherries and magnesium.', 'both'),
('inseason', 'Keep immune-supporting foods in your diet during the grind.', 'both'),
('inseason', 'Prepare meals ahead for busy game-day schedules.', 'both'),
('inseason', 'Eat a substantial breakfast on game days.', 'both'),
('inseason', 'Pre-game meals should be 3-4 hours before first pitch.', 'both'),
('inseason', 'Small snacks between games during doubleheaders are essential.', 'both'),
('inseason', 'Avoid heavy, fatty foods that slow digestion before games.', 'both'),
('inseason', 'Carbohydrate intake should match training intensity.', 'both'),
('inseason', 'Monitor body weight weekly to ensure adequate calorie intake.', 'both'),
('inseason', 'In-season supplements should focus on recovery and immune support.', 'both'),
('inseason', 'Communicate nutrition needs to coaches and trainers.', 'both'),
('inseason', 'Eat something within 30 minutes after games, even if not hungry.', 'both'),
('inseason', 'Tournament weekends require extra planning for nutrition.', 'softball'),
('inseason', 'Dont skip meals during busy game weeks.', 'both'),
('inseason', 'Keep protein intake consistent to maintain muscle mass.', 'both'),
('inseason', 'Adjust sodium intake based on sweat losses and weather.', 'both'),
('inseason', 'Have go-to restaurants that offer healthy options for road games.', 'both'),
('inseason', 'Listen to your body - fatigue may indicate inadequate nutrition.', 'both'),

-- Performance Priming (30 tips)
('performance', 'Carb loading the day before competition can improve endurance.', 'both'),
('performance', 'Caffeine 30-60 minutes before games can enhance alertness and performance.', 'both'),
('performance', 'Beet juice 2-3 hours before competition may improve oxygen efficiency.', 'both'),
('performance', 'Pre-game meals should be high carb, moderate protein, low fat.', 'both'),
('performance', 'Avoid high-fiber foods before games to prevent GI distress.', 'both'),
('performance', 'Familiar foods reduce the risk of stomach issues during competition.', 'both'),
('performance', 'Mental preparation and nutrition work together for peak performance.', 'both'),
('performance', 'Creatine supplementation can improve power output in sprints.', 'both'),
('performance', 'Beta-alanine may improve performance in high-intensity activities.', 'both'),
('performance', 'Adequate sleep the week before big games is crucial.', 'both'),
('performance', 'Visualize success while eating your pre-game meal.', 'both'),
('performance', 'Avoid alcohol for at least 48 hours before important competitions.', 'both'),
('performance', 'Test any new performance nutrition strategies during practice first.', 'both'),
('performance', 'Nervous stomachs may do better with liquid nutrition before games.', 'both'),
('performance', 'Banana and peanut butter is a classic pre-game snack.', 'both'),
('performance', 'Oatmeal provides sustained energy for morning games.', 'both'),
('performance', 'Rice and chicken is easy to digest before afternoon games.', 'both'),
('performance', 'Avoid spicy foods the day before and day of competition.', 'both'),
('performance', 'Energy gels or chews can provide quick fuel during long games.', 'both'),
('performance', 'Positive self-talk combined with proper nutrition builds confidence.', 'both'),
('performance', 'Warm-up snacks should be easily digestible.', 'both'),
('performance', 'Tart cherry juice before games may improve recovery.', 'both'),
('performance', 'Hydrate well the day before to start competition optimally hydrated.', 'both'),
('performance', 'Performance anxiety can affect digestion - plan accordingly.', 'both'),
('performance', 'Evening games allow for larger, earlier meals.', 'both'),
('performance', 'Morning games require earlier wake times for proper nutrition timing.', 'both'),
('performance', 'Have a pre-game routine that includes consistent nutrition.', 'both'),
('performance', 'Pitchers may need lighter pre-start meals than position players.', 'baseball'),
('performance', 'Catchers should eat to sustain energy throughout the entire game.', 'baseball'),
('performance', 'Playoff nutrition should mirror successful regular season habits.', 'both'),

-- In-Game Hydration (25 tips)
('ingame_hydration', 'Take small sips between innings rather than chugging large amounts.', 'both'),
('ingame_hydration', 'Sports drinks are appropriate during games lasting over 60 minutes.', 'both'),
('ingame_hydration', 'Electrolyte tablets can be added to water during hot games.', 'both'),
('ingame_hydration', 'Avoid carbonated beverages during games as they can cause bloating.', 'both'),
('ingame_hydration', 'Cold beverages may be absorbed faster than room temperature.', 'both'),
('ingame_hydration', 'Know where water stations are located in your dugout.', 'both'),
('ingame_hydration', 'Designate teammates to remind each other to hydrate.', 'both'),
('ingame_hydration', 'Pitchers should drink between every inning without exception.', 'baseball'),
('ingame_hydration', 'Catchers should remove gear and hydrate between innings.', 'baseball'),
('ingame_hydration', 'Position players should hydrate while in the field during timeouts.', 'both'),
('ingame_hydration', 'Sunflower seeds can cause dehydration - balance with extra water.', 'both'),
('ingame_hydration', 'Gum chewing during games does not replace fluid intake.', 'both'),
('ingame_hydration', 'Energy drinks are not appropriate for in-game hydration.', 'both'),
('ingame_hydration', 'Fruit slices like oranges provide hydration and quick energy.', 'both'),
('ingame_hydration', 'Monitor teammates for signs of dehydration during hot games.', 'both'),
('ingame_hydration', 'Dark urine during games is a red flag for dehydration.', 'both'),
('ingame_hydration', 'Misting with water can help cool the body without filling the stomach.', 'both'),
('ingame_hydration', 'Ice towels on the neck can reduce core temperature.', 'both'),
('ingame_hydration', 'Pre-cooling with cold beverages before hot games can help.', 'both'),
('ingame_hydration', 'Dont wait until youre thirsty - drink on a schedule.', 'both'),
('ingame_hydration', 'Night games in hot climates still require diligent hydration.', 'both'),
('ingame_hydration', 'Humidity increases fluid needs even more than dry heat.', 'both'),
('ingame_hydration', 'Rain delays are good opportunities to reassess hydration status.', 'both'),
('ingame_hydration', 'Extra innings require additional hydration planning.', 'both'),
('ingame_hydration', 'Doubleheaders require hydration planning between games.', 'both'),

-- NSF Supplements (25 tips)
('supplements', 'NSF Certified for Sport products are tested for banned substances.', 'both'),
('supplements', 'Informed Sport certification also indicates third-party testing.', 'both'),
('supplements', 'Whey protein is well-researched for muscle building and recovery.', 'both'),
('supplements', 'Creatine monohydrate is one of the most researched supplements.', 'both'),
('supplements', 'Caffeine is a legal performance enhancer with strong research support.', 'both'),
('supplements', 'Fish oil provides omega-3s when dietary intake is insufficient.', 'both'),
('supplements', 'Vitamin D supplementation is often necessary for indoor athletes.', 'both'),
('supplements', 'Probiotics may support gut health and immune function.', 'both'),
('supplements', 'Tart cherry supplements support recovery and sleep.', 'both'),
('supplements', 'Collagen peptides may support joint and connective tissue health.', 'both'),
('supplements', 'Beetroot powder provides nitrates for improved blood flow.', 'both'),
('supplements', 'Electrolyte supplements help replace losses from sweat.', 'both'),
('supplements', 'Melatonin can help with sleep when traveling across time zones.', 'both'),
('supplements', 'Magnesium supplementation may help with muscle relaxation and sleep.', 'both'),
('supplements', 'Zinc lozenges may reduce duration of colds.', 'both'),
('supplements', 'Most athletes dont need testosterone boosters - focus on basics first.', 'both'),
('supplements', 'Pre-workout supplements should be used cautiously and sparingly.', 'both'),
('supplements', 'Mass gainers are only necessary if struggling to eat enough calories.', 'both'),
('supplements', 'BCAAs may be useful during fasted training but not essential.', 'both'),
('supplements', 'HMB may help preserve muscle during caloric restriction.', 'both'),
('supplements', 'Beta-alanine can cause tingling but is generally safe.', 'both'),
('supplements', 'Citrulline may improve blood flow and exercise performance.', 'both'),
('supplements', 'Ashwagandha may help manage training stress.', 'both'),
('supplements', 'Always check supplements against your sports banned substance list.', 'both'),
('supplements', 'When in doubt, consult a sports dietitian about supplements.', 'both'),

-- Holistic Health (30 tips)
('holistic', 'Mind-body practices like meditation complement physical nutrition.', 'both'),
('holistic', 'Gratitude practice can improve mental health and eating behaviors.', 'both'),
('holistic', 'Stress reduction improves digestion and nutrient absorption.', 'both'),
('holistic', 'Connection with nature supports overall well-being.', 'both'),
('holistic', 'Social eating with teammates builds community and improves nutrition habits.', 'both'),
('holistic', 'Sleep hygiene is as important as nutrition for performance.', 'both'),
('holistic', 'Journaling can help identify emotional eating patterns.', 'both'),
('holistic', 'Breathing exercises before meals improve digestion.', 'both'),
('holistic', 'Positive relationships with food prevent disordered eating.', 'both'),
('holistic', 'Body awareness helps you eat intuitively based on true hunger.', 'both'),
('holistic', 'Seasonal eating aligns nutrition with natural cycles.', 'both'),
('holistic', 'Growing your own herbs connects you to your food.', 'both'),
('holistic', 'Cooking can be a meditative and stress-reducing practice.', 'both'),
('holistic', 'Eating without screens improves mindfulness and digestion.', 'both'),
('holistic', 'Circadian rhythm eating aligns meals with natural light cycles.', 'both'),
('holistic', 'Earthing or grounding may reduce inflammation and improve sleep.', 'both'),
('holistic', 'Cold exposure through cold showers may improve recovery.', 'both'),
('holistic', 'Heat exposure through saunas supports detoxification.', 'both'),
('holistic', 'Acupuncture may complement nutrition for certain conditions.', 'both'),
('holistic', 'Massage therapy supports muscle recovery and relaxation.', 'both'),
('holistic', 'Chiropractic care may improve nerve function and digestion.', 'both'),
('holistic', 'Aromatherapy with peppermint can aid digestion.', 'both'),
('holistic', 'Lavender aromatherapy supports sleep and relaxation.', 'both'),
('holistic', 'Sound therapy and music can reduce stress and improve eating.', 'both'),
('holistic', 'Color therapy suggests eating a rainbow of foods.', 'both'),
('holistic', 'Energy healing practices may complement physical nutrition.', 'both'),
('holistic', 'Spiritual practices provide meaning that supports healthy choices.', 'both'),
('holistic', 'Community support improves adherence to nutrition goals.', 'both'),
('holistic', 'Self-compassion prevents negative self-talk around food choices.', 'both'),
('holistic', 'Holistic health views nutrition as one part of overall wellness.', 'both');