
INSERT INTO public.wk_movement_catalog (
  slug, name, category, pattern, family, movement_pattern, movement_category,
  intensity_class, primary_adaptation, secondary_adaptation,
  cns_cost, joint_stress, recovery_cost, volume_cost,
  equipment, min_age_years, min_training_age_years,
  phase_allow, season_eligibility,
  power_emphasis, elastic_emphasis, speed_emphasis,
  pap_classification, movement_velocity,
  default_sets, default_reps, cue, why_prescribed,
  wic_metadata_complete, game_day_eligible, source_philosophy, evidence_note
) VALUES
-- ---- LOWER: assisted / overspeed expressions (French contrast station 4) ----
('lift_band_assisted_vertical_jump','Band-Assisted Vertical Jump','strength','hinge_squat','hinge','hinge_squat','compound_lower','high','power','speed',2,2,2,2,
 ARRAY['bands','rack'],16,3,
 ARRAY['os_q2','os_q3','os_q4'],ARRAY['os_q2','os_q3','os_q4'],
 true,true,true,'assisted','ballistic',3,3,
 'Let the band pull you — stay tall, land quiet, reset every rep.',
 'Overspeed expression after heavy work: the nervous system fires at a rate you cannot reach unloaded.',
 true,false,'contrast_training','Assisted jumps raise peak unloading velocity; used as the terminal station of French contrast.'),
('lift_overspeed_band_squat_jump','Overspeed Band Squat Jump','strength','hinge_squat','hinge','hinge_squat','compound_lower','high','power','speed',2,2,2,2,
 ARRAY['bands','rack'],16,3,
 ARRAY['os_q2','os_q3','os_q4'],ARRAY['os_q2','os_q3','os_q4'],
 true,true,true,'assisted','ballistic',3,3,
 'Ride the band up. Minimum ground time, maximum intent.',
 'Terminal overspeed station — teaches the hips to move faster than gravity allows.',
 true,false,'contrast_training','Overspeed conditions bias rate-of-force development after potentiation.'),
('lift_drop_jump_rebound_assisted','Assisted Drop Jump Rebound','strength','hinge_squat','hinge','hinge_squat','compound_lower','high','power','elastic',2,3,2,2,
 ARRAY['box','bands'],16,3,
 ARRAY['os_q2','os_q3','os_q4'],ARRAY['os_q2','os_q3','os_q4'],
 true,true,true,'assisted','ballistic',3,3,
 'Step off, do not jump off. Touch and go — the floor is hot.',
 'Reactive terminal station: short ground contact under assistance protects the joints while chasing stiffness.',
 true,false,'contrast_training','Drop-jump rebounds train the stretch-shortening cycle; assistance caps landing load.'),
-- ---- UPPER PUSH: plyometric + assisted stations ----
('lift_clap_pushup_plyo','Clap Push-Up','strength','horizontal_push','push','horizontal_push','compound_upper_push','high','power','elastic',2,2,2,2,
 ARRAY[]::text[],16,2,
 ARRAY['os_q2','os_q3','os_q4'],ARRAY['os_q2','os_q3','os_q4'],
 true,true,false,'plyometric','ballistic',3,4,
 'Push the floor away. Catch soft with the elbows, never the chest.',
 'Plyometric upper-push station: converts bench strength into throwing-relevant push speed.',
 true,false,'contrast_training','Ballistic push-ups are the standard upper-body plyometric contrast station.'),
('lift_depth_drop_pushup','Depth Drop Push-Up','strength','horizontal_push','push','horizontal_push','compound_upper_push','high','power','elastic',2,3,2,2,
 ARRAY['box'],16,3,
 ARRAY['os_q3','os_q4'],ARRAY['os_q3','os_q4'],
 true,true,false,'plyometric','ballistic',3,3,
 'Drop, absorb, explode. Chest never touches the floor.',
 'High-intent plyometric push station reserved for advanced athletes in the power quarters.',
 true,false,'contrast_training','Depth drops maximize eccentric loading for upper-body reactive strength.'),
('lift_band_assisted_plyo_pushup','Band-Assisted Plyo Push-Up','strength','horizontal_push','push','horizontal_push','compound_upper_push','high','power','speed',2,2,2,2,
 ARRAY['bands'],16,2,
 ARRAY['os_q2','os_q3','os_q4'],ARRAY['os_q2','os_q3','os_q4'],
 true,true,true,'assisted','ballistic',3,4,
 'Let the band unload you — chase air time, not reps.',
 'Overspeed upper-push finisher: assistance raises bar velocity beyond what bodyweight allows.',
 true,false,'contrast_training','Assisted ballistic push-ups extend the velocity end of the force-velocity curve.'),
('lift_overspeed_band_bench_throw','Overspeed Band Bench Throw','strength','horizontal_push','push','horizontal_push','compound_upper_push','high','power','speed',2,2,2,2,
 ARRAY['bands','smith','barbell'],16,4,
 ARRAY['os_q3','os_q4'],ARRAY['os_q3','os_q4'],
 true,false,true,'assisted','ballistic',3,3,
 'Accelerate through the top. Bands do the catching, not your elbows.',
 'Terminal overspeed press station — only inside a rack or Smith with band capture.',
 true,false,'contrast_training','Band-assisted throws are the safest way to express supra-maximal press velocity.'),
-- ---- UPPER PULL: assisted / overspeed stations ----
('lift_band_assisted_explosive_pullup','Band-Assisted Explosive Pull-Up','strength','vertical_pull','pull','vertical_pull','compound_upper_pull','high','power','speed',2,2,2,2,
 ARRAY['bands','rack'],16,2,
 ARRAY['os_q2','os_q3','os_q4'],ARRAY['os_q2','os_q3','os_q4'],
 true,true,true,'assisted','ballistic',3,4,
 'Chin over bar fast. The band buys you speed, not rest.',
 'Overspeed pull station — trains the back to contract at competition speed after heavy pulling.',
 true,false,'contrast_training','Assisted ballistic pull-ups preserve intent when fatigue would otherwise slow the bar.'),
('lift_overspeed_band_row','Overspeed Band Row','strength','horizontal_pull','pull','horizontal_pull','compound_upper_pull','high','power','speed',2,2,2,2,
 ARRAY['bands'],16,2,
 ARRAY['os_q2','os_q3','os_q4'],ARRAY['os_q2','os_q3','os_q4'],
 true,false,true,'assisted','ballistic',3,6,
 'Rip the handle to the ribs. Control the return, snap the pull.',
 'Velocity-end pull station that keeps the deceleration muscles fast, not just strong.',
 true,false,'contrast_training','High-velocity rowing supports arm deceleration capacity in throwers.')
ON CONFLICT (slug) DO NOTHING;
