
WITH seed(sport, name, description, ai_context, level, positions, tag_names, instructions) AS (
VALUES
('baseball','One-Knee Stab Receiving','Steal called strikes by beating the ball to the spot with a still body and quiet mitt.','Elite framing: quiet chest, loud glove — no jab, no swipe.',6,ARRAY['C'],ARRAY['catcher','fielding_mechanics'],
 '{"purpose":"Steal called strikes on the low edge by beating the ball to the spot instead of catching it into your body.","setup":["One-knee stance (glove-side knee down), mitt-hand relaxed at knee height.","Coach or machine at 45 ft, 30 balls per set: 10 low-mid, 10 low-glove, 10 low-arm."],"execution":["Set mitt open at the bottom edge of the zone.","As ball enters, load thumb under and receive TOWARD the zone, not away from it.","Freeze mitt for a full second inside the zone before returning to target."],"coaching_cues":["Beat the ball to the spot","Catch it moving to the zone","Thumb under on the bottom","Quiet chest, loud glove"],"mistakes":["Jabbing at the ball (mitt drifts away from the zone).","Head dropping under low pitches — umpires read the body, not just the glove.","Elbow flying out on arm-side pitches."],"success_markers":["≥8/10 low pitches received without mitt drift below the zone.","Umpire-view video shows a still head and single-plane mitt path.","Freeze held ≥1 second on every rep."],"progression":["Regression: partner tosses at 30 ft, verbal-call only.","Base: machine at 45 ft, low-corner sequence.","Advanced: live BP with a hitter blocking sight line."]}'::jsonb),
('baseball','Lateral Block Ladder','Own the dirt by turning body-first blocks into balls that land in front, not off to the side.','Blocking priority: chest to ball, chin down, ball dies in the box.',6,ARRAY['C'],ARRAY['catcher','fielding_mechanics'],
 '{"purpose":"Kill balls in the dirt so runners never advance — angle and chest, not glove and pray.","setup":["Full gear. Coach with a bucket at 25 ft throwing short-hop 55-ft pitches.","5-round ladder: direct, glove-side 1 step, arm-side 1 step, glove-side 2 step, arm-side 2 step. 6 balls per round."],"execution":["Read hop, drop to both knees while driving hip to the ball\u2019s line.","Chin tucks to chest, glove seals the 5-hole, forearms angle ball into the box.","Recover to feet with ball visible and secured in bare hand."],"coaching_cues":["Beat the ball to the line","Chin to chest","Kill it — don\u2019t catch it","Recover with the ball in your hand"],"mistakes":["Reaching sideways with the glove instead of moving the body.","Chin up so ball ricochets off the mask.","Losing sight of the ball on recovery."],"success_markers":["Ball lands inside a 3-ft box in front of the plate on ≥80% of reps.","No pass-throughs across the round.","Recovery in ≤1.5 sec with ball secured."],"progression":["Regression: knee starts, no lateral movement.","Base: 1-step ladder.","Advanced: 2-step ladder + throw to a base after every block."]}'::jsonb),
('baseball','Quick-Hands Transfer Under Stopwatch','Cut tenths off pop time by making the exchange the fastest part of your throw.','Transfer target: 0.65 s or less from catch to release load.',6,ARRAY['C'],ARRAY['catcher','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Compress transfer time so a 1.9 pop time is repeatable, not an outlier.","setup":["Full gear, partner at 45 ft flipping fastballs into the mitt.","Stopwatch or video with per-frame markers. 20-rep set."],"execution":["Receive with soft hands, mitt already turning to the sternum.","Bare hand meets mitt at center chest — no glove-then-hand hand-off.","Load into a 4-seam grip on the way up, throwing shoulder ahead of the hip."],"coaching_cues":["Meet in the middle","Grip on the way up","No look — feel","Load, don\u2019t wind up"],"mistakes":["Waiting for the ball to hit the pocket before starting the transfer.","Rotating the mitt down (grip is buried).","Snatching the ball out — grip is inconsistent."],"success_markers":["Transfer ≤0.70 s on 8/10 reps.","4-seam grip on ≥90% of throws.","No dropped exchanges across 20 reps."],"progression":["Regression: dry transfers, no throw.","Base: transfer + throw to a net at 60 ft.","Advanced: full pop time to 2B with runner."]}'::jsonb),
('baseball','Pop-Time Gauntlet','Pressure-test pop time under fatigue and randomized pitch locations.','Elite target: sub-1.95 pop time with strike accuracy 4/5.',7,ARRAY['C'],ARRAY['catcher','throwing_accuracy'],
 '{"purpose":"Turn game-speed pop times into a habit under fatigue, not a peak-effort feat.","setup":["Full gear, partner at 55 ft throwing to random locations (arm-side, glove-side, low).","Runner or cone at 2B; timer on release-to-catch."],"execution":["Set 5 rounds of 5 throws with 20 s rest.","Every throw is game-speed to 2B, tag ready.","Log pop time and accuracy (in/out of the tag zone)."],"coaching_cues":["Same throw every rep","Feet do the aiming","Trust the transfer","Release, don\u2019t muscle"],"mistakes":["Overthrowing the second round to make up for the first.","Aiming with the arm instead of the plant foot.","Long backswing under fatigue."],"success_markers":["Round-1 vs round-5 pop time drop ≤0.05 s.","≥18/25 throws inside the tag zone.","Grip clean on every throw."],"progression":["Regression: 3-round set from a knee.","Base: full 5-round gauntlet.","Advanced: live pitcher, hitter in box."]}'::jsonb),
('baseball','Backpick to 1B','Steal outs off big leads by adding an accurate short-arm snap throw to 1B.','Backpick angle: catcher steps around the RHH, throws over the inside corner.',7,ARRAY['C'],ARRAY['catcher','throwing_accuracy'],
 '{"purpose":"Punish sleepy runners at 1B without giving up a passed ball.","setup":["Full gear, hitter (or dummy) in the RHH box, 1B holding a target.","20 reps: 10 with hitter still, 10 with hitter loading."],"execution":["Receive pitch, jab-step behind the hitter\u2019s back foot.","Short-arm release from ear — no full windup.","Aim for the inside corner of the 1B bag, glove-side of the runner."],"coaching_cues":["Step around, not through","Short arm, quick fingers","Bag corner, not the belt buckle","Read the lead, then commit"],"mistakes":["Throwing into the hitter\u2019s back on the load.","Long stride that kills quickness.","Aiming at the runner instead of the bag."],"success_markers":["≥8/10 throws inside a 2-ft box on the inside corner.","No hit-a-hitter interference reps.","Release ≤1.0 s from catch."],"progression":["Regression: from a knee, no jab step.","Base: full backpick, no hitter.","Advanced: hitter loads on every rep, live pitcher."]}'::jsonb),
('baseball','Bunt Pop-and-Plant','Turn bunts into outs by leaving the crouch faster than the hitter leaves the box.','Priority: read direction, pop, plant, throw — not scoop-and-hope.',6,ARRAY['C'],ARRAY['catcher','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Convert bunts into recorded outs by beating the hitter\u2019s first step out of the box.","setup":["Full gear, coach rolls or bunts balls into the 5\u201310 ft zone in front of the plate.","3 targets: 1B, 2B, 3B. 24-rep set (8 to each base)."],"execution":["Read direction as ball leaves the bat.","Explode from crouch with mask off, glove-hand leads.","Field with the throwing hand on top, plant on the base-side foot, release from a strong platform."],"coaching_cues":["Mask off, eyes up","Field with two hands, not one","Plant, then throw","Feet decide the base"],"mistakes":["Scooping one-handed and losing the ball.","Throwing off the wrong foot.","Committing to a base before seeing the ball."],"success_markers":["Clean field + on-line throw ≥80% of reps.","Bare-hand-and-flip only used when required by ball position.","Release ≤1.4 s from field-to-throw."],"progression":["Regression: no throw — just field and set feet.","Base: full pop, plant, throw to 1B.","Advanced: random base call on ball contact."]}'::jsonb),
('baseball','Framing Edge Ladder','Turn borderline pitches into strikes on all four zone edges.','Movement to the zone — never the other way.',5,ARRAY['C'],ARRAY['catcher','fielding_mechanics'],
 '{"purpose":"Own the four edges of the zone with the same quiet mitt path from every angle.","setup":["One-knee stance. Machine at 45 ft. 40 balls: 10 top, 10 bottom, 10 arm-side, 10 glove-side edges."],"execution":["Set target at the middle of the zone.","Receive each edge pitch moving the mitt one inch into the zone at contact.","Freeze 1 second, then return."],"coaching_cues":["Beat the ball to the spot","One inch into the zone","Chest still, mitt loud","Freeze before you reset"],"mistakes":["Swipe framing (mitt moves parallel, not into).","Head follows the mitt.","Freeze skipped on obvious strikes."],"success_markers":["Ump-view video: mitt ends inside the zone on ≥90% of borderline pitches.","No head bounce across the set.","Freeze visible on every rep."],"progression":["Regression: verbal only, no mitt movement.","Base: 4-corner ladder.","Advanced: live BP, hitter as blocker."]}'::jsonb),
('baseball','Pitch-in-Dirt Read Progression','Build instant hop-recognition so blocks are proactive, not reactive.','Read the pitcher\u2019s slot, then the hop — anticipate the block before the release.',6,ARRAY['C'],ARRAY['catcher','fielding_mechanics'],
 '{"purpose":"Recognize dirt-bound pitches earlier so blocks are set up before the bounce, not chased after it.","setup":["Full gear. Machine or coach delivers a mixed sequence of strikes and short-hop pitches (2:1 ratio).","30-rep set."],"execution":["Call the pitch type in your head before every delivery.","On dirt reads, drop and seal before the ball hits the ground.","On strikes, receive quietly."],"coaching_cues":["See the release, not the ball","Drop early, freeze late","Chin to chest on every dirt read","Nothing behind you"],"mistakes":["Reacting to the bounce instead of the release.","Half-drops that leak between the legs.","Freezing on strikes (over-anticipation)."],"success_markers":["0 pass-throughs across the set.","≤10% false drops on true strikes.","Every dirt read blocked in front of the plate."],"progression":["Regression: coach announces dirt/strike before pitch.","Base: mixed sequence.","Advanced: live pitcher, unknown mix."]}'::jsonb),
('baseball','Tag Play at the Plate — Sweep Ladder','Convert throws home into outs without losing the ball or the lane.','Give the runner the corner, take away the plate.',6,ARRAY['C'],ARRAY['catcher','fielding_mechanics'],
 '{"purpose":"Apply a clean, rule-legal tag at home on true, offline, and short-hop throws.","setup":["Full gear. Partner throws from CF cutoff distance (85 ft).","3 rounds: true throw, up-the-line, offline. 6 reps each."],"execution":["Straddle the front corner of the plate, glove flat between plate and third-base line.","Receive the ball, sweep across the runner\u2019s slide lane.","Present ball to umpire after every tag."],"coaching_cues":["Feet outside the plate","Sweep, don\u2019t chop","Ball first, tag second","Show the ump"],"mistakes":["Blocking the plate before the ball arrives (illegal).","Reaching across the runner\u2019s helmet.","Losing the ball on the tag."],"success_markers":["Tag applied without dropping ball on ≥90% of reps.","No blocking-the-plate calls.","Ump-facing ball presentation on every tag."],"progression":["Regression: stationary receive-and-tag.","Base: 3-round ladder.","Advanced: sliding runner with pads."]}'::jsonb),
('baseball','Pickoff Footwork vs LH/RH','Steal outs at 1B and 3B by matching your footwork to the runner\u2019s side.','Footwork rule: base-side foot leads the throw.',7,ARRAY['C'],ARRAY['catcher','throwing_accuracy'],
 '{"purpose":"Own catcher pickoffs at 1B and 3B without a false step or a throwing-lane mistake.","setup":["Full gear, dummy hitter in each box on alternating reps.","20 reps: 10 pickoffs to 1B (RHH in box), 10 to 3B (LHH in box)."],"execution":["Receive pitch, jab-step around the hitter with the base-side foot.","Short-arm release from the ear.","Follow throw with a controlled recovery — no lunging."],"coaching_cues":["Jab, don\u2019t drift","Base-side foot leads","Short arm, high finger release","Recover to blocking posture"],"mistakes":["Stepping into the hitter\u2019s body.","Full windup on a short throw.","Losing balance after release."],"success_markers":["≥8/10 throws inside a 2-ft box at the bag.","No interference reps.","Release ≤1.0 s from catch."],"progression":["Regression: dry footwork, no throw.","Base: full pickoff, no hitter.","Advanced: hitter loads on every rep, coach calls base at random."]}'::jsonb),
('baseball','Throw-Down Under Fatigue','Ensure pop time survives a 3-hour game, not just a fresh warm-up.','Test conditioning inside the position — no gassed 7th-inning throws.',7,ARRAY['C'],ARRAY['catcher','throwing_accuracy'],
 '{"purpose":"Keep pop time stable in innings 6\u20139 when the legs are the first thing to leave.","setup":["Full gear. 4 sets of 5 throws to 2B with 30 s block work between each throw.","Timer + accuracy log."],"execution":["Block 2 pitches, then throw one to 2B, repeat.","Focus stays on plant-foot direction, not arm effort.","Rest 60 s between sets."],"coaching_cues":["Legs stay under you","Same throw every rep","Feet aim, arm delivers","Breathe through the block"],"mistakes":["Arming the throw when the legs die.","Rushing after a block.","Grip breakdown in later sets."],"success_markers":["Pop time drift ≤0.05 s from set 1 to set 4.","≥16/20 throws inside the tag zone.","Grip stays 4-seam on ≥90% of throws."],"progression":["Regression: 2-set version.","Base: 4-set full circuit.","Advanced: live pitcher, hitter in box."]}'::jsonb),
('softball','One-Knee Stab Receiving — Softball','Steal called strikes in the rise-heavy softball zone with a still body and quiet mitt.','Softball priority: catch the rise moving UP into the zone.',6,ARRAY['C'],ARRAY['catcher','fielding_mechanics'],
 '{"purpose":"Steal borderline high strikes in softball\u2019s rise-heavy zone with a quiet, mitt-into-the-zone path.","setup":["One-knee stance. Machine at 40 ft. 30 balls: 10 top-of-zone rise, 10 low corners, 10 arm/glove-side edges."],"execution":["Set target inside the top of the zone.","On rise pitches, load thumb up and catch mitt moving TOWARD the zone.","Freeze 1 second before returning to target."],"coaching_cues":["Beat the rise to the spot","Thumb up on the top","Quiet chest","Freeze, then reset"],"mistakes":["Reaching up and pulling the ball out of the zone.","Head jerking with the rise.","No freeze on borderline pitches."],"success_markers":["Ump-view video: mitt inside the top of zone on ≥8/10 rise pitches.","Head bounce zero across set.","Freeze visible on every rep."],"progression":["Regression: 30 ft partner tosses.","Base: machine at 40 ft.","Advanced: live rise-ball pitcher."]}'::jsonb),
('baseball','Glove-Side Funnel','Turn every ball hit at you into a clean transfer without popping straight up.','Elite infield: field it in a triangle, transfer at the belly, throw from a strong platform.',5,ARRAY['2B','SS','MI','IF'],ARRAY['infield','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Field the ball inside a stable triangle so the transfer is quiet and the throw stays on-line.","setup":["Coach fungoes 20 grounders straight at the fielder from 60 ft.","Cone at the throwing shoulder to check upright posture on recovery."],"execution":["Read hop, get chest over ball, glove hand slightly ahead of throwing hand.","Funnel ball to the belly button — both hands together.","Take a directional step toward the throwing target, then release."],"coaching_cues":["Chest over the ball","Funnel to the belly, not the chest","Directional step, then throw","Two hands on the field, two hands on the transfer"],"mistakes":["Popping up before the ball is secured.","Fielding out in front with one hand.","Rotating away from the target on the transfer."],"success_markers":["Clean-field-clean-throw on ≥18/20 reps.","No pop-ups before secure catch.","Throwing shoulder finishes at target line."],"progression":["Regression: rolled grounders at walking pace.","Base: full fungo speed.","Advanced: 2-ball rapid sequence."]}'::jsonb),
('baseball','Backhand Shuffle-Replace','Steal outs on balls in the 5–6 hole with a coach-clean backhand approach.','Best backhand fielders replace feet before they field the ball.',6,ARRAY['SS','MI','3B','CI','IF'],ARRAY['infield','fielding_mechanics'],
 '{"purpose":"Own the 5\u20136 hole with an efficient shuffle-replace footwork pattern instead of a lunge.","setup":["Coach fungoes to the backhand side from 60 ft. 20 reps."],"execution":["First step is a shuffle, not a cross-over — replace the right foot with the left.","Reach with the glove-side arm extended, thumb down.","Plant back foot, drive off it into a directional throw."],"coaching_cues":["Shuffle to replace","Thumb down, glove big","Plant, then explode","Throw from a strong platform"],"mistakes":["Crossing over on the first step (kills recovery).","Fielding off the back foot without a plant.","Throwing across the body without hips."],"success_markers":["Clean field on ≥16/20 backhand reps.","Plant-foot recovery on every rep — no drop-throws.","Throw on target to 1B ≥14/20."],"progression":["Regression: dry footwork, no ball.","Base: fungoed backhand.","Advanced: live cross-court short-hop."]}'::jsonb),
('baseball','Double-Play Feed Ladder','Master all four DP feeds so the pivot always gets a catchable ball.','Feed rule: match your feet to the distance.',6,ARRAY['2B','SS','MI','IF'],ARRAY['infield','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Deliver a catchable feed to the pivot from every fielding position in a 6-4-3 or 4-6-3.","setup":["Partner at 2B as pivot. Coach fungoes rounds of 5 balls: (1) glove-side flip, (2) chest-height turn, (3) dart throw, (4) behind-the-back."],"execution":["Read hop, choose feed based on distance and body position.","Feed target: chest-high, over the front-side hip of the pivot.","Follow feed with 1\u20132 recovery steps to stay in the play."],"coaching_cues":["Match feet to feed","Chest-high, hip-side","Quiet feed, loud throw at 1B","Never one-hand what two hands could do"],"mistakes":["Flipping when a dart is needed (or vice versa).","Feed to the pivot\u2019s back shoulder.","Standing still after the feed."],"success_markers":["Catchable feed on ≥18/20 reps.","Feed at chest height on ≥85% of reps.","Recovery step visible on every rep."],"progression":["Regression: stationary partner tosses.","Base: full ladder.","Advanced: live runner pressure on the pivot."]}'::jsonb),
('baseball','Pivot at 2B Under Runner Pressure','Turn the second half of a DP with the runner bearing down.','Pivot rule: catch, clear, throw — never turn your back on the ball.',7,ARRAY['2B','MI','IF'],ARRAY['infield','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Complete the DP turn while managing an aggressive slide.","setup":["Runner (or pad) sliding at second. Feeder throws chest-high from SS position.","3 turn styles: over-the-bag, inside pivot, straddle. 6 reps each."],"execution":["Meet the bag with the throwing-side foot.","Catch, clear the bag with a controlled step, and throw across the runner\u2019s helmet path.","Keep eyes on the target through release."],"coaching_cues":["Meet the bag on the throw side","Clear the slide lane","Throw over the helmet","Finish balanced, not backing up"],"mistakes":["Standing on the bag through the throw.","Throwing off the wrong foot into the runner\u2019s slide.","Turning the head away from the target."],"success_markers":["Throw on-line to 1B on ≥16/18 reps.","No unbalanced landings on the pivot.","Eyes stay on target through release."],"progression":["Regression: pivot without a runner.","Base: pad slider on every rep.","Advanced: live runner with real cleats."]}'::jsonb),
('baseball','Slow-Roller Barehand Attack','Punish weak contact with a full-speed barehand + on-the-run throw.','Slow-roller rule: charge angle > glove technique.',6,ARRAY['SS','3B','2B','MI','CI','IF'],ARRAY['infield','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Convert slow rollers into outs by using the correct charge angle and a barehand release.","setup":["Coach rolls slow topspin balls from 60 ft.","15 reps to 1B, on-the-run release only."],"execution":["Charge at a 45\u00b0 angle that keeps you inside the base line.","Field with barehand on the outside of the ball, throw as the throwing-side foot plants.","No stop, no set."],"coaching_cues":["Charge at 45","Barehand outside the ball","Throw off the plant, not the stop","Follow through toward 1B"],"mistakes":["Running through the ball.","Trying to glove-field a ball meant for the barehand.","Full stop before throw."],"success_markers":["Barehand catch on ≥12/15 reps.","On-line throw to 1B on ≥10/15 reps.","No stopped reps."],"progression":["Regression: barehand dry drill (no throw).","Base: live slow rollers.","Advanced: with runner timing."]}'::jsonb),
('baseball','In-Between Hop Read','Eliminate the killer in-between hop by moving your feet, not your glove.','No such thing as an in-between hop — only feet that arrived late.',5,ARRAY['SS','2B','3B','MI','CI','IF'],ARRAY['infield','fielding_mechanics'],
 '{"purpose":"Turn every hop into a big hop or a short hop by moving your feet on the read.","setup":["Coach fungoes at unpredictable distances so the ball would land in between the fielder\u2019s feet.","20 reps."],"execution":["Read the ball off the bat — accelerate forward or drop-step back to force a chosen hop.","Field the chosen hop clean, transfer to target.","Never freeze."],"coaching_cues":["Kill the in-between","Feet decide the hop","Attack or retreat — never wait","Field the hop you chose"],"mistakes":["Stopping and reaching (bad hand-eye guess).","Choosing wrong direction and lunging.","Fielding off balance."],"success_markers":["Feet moved on ≥19/20 reps.","Clean-field ≥16/20.","Balanced throw finish on every rep."],"progression":["Regression: rolled at slow pace.","Base: full fungo.","Advanced: chaos fungos with random cadence."]}'::jsonb),
('baseball','Deep-Hole SS Plant-and-Throw','Convert deep-hole balls with a jump-throw or plant-throw from a strong platform.','Elite deep hole: brake with the right foot, load, jump, throw.',7,ARRAY['SS'],ARRAY['infield','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Turn the deep hole into a routine out with a jump-throw or plant-throw.","setup":["Coach fungoes to the deep 5\u20136 hole from 60 ft. 15 reps."],"execution":["Field deep with backhand extended.","Brake with the right foot, load the hip.","Jump throw across the body — release from ear, land balanced."],"coaching_cues":["Brake, load, jump","Release from the ear","Land balanced, not falling","Follow through to 1B"],"mistakes":["Falling away from target on release.","Trying to run to the target and losing arm strength.","Missing the plant foot."],"success_markers":["On-line throw to 1B on ≥10/15 reps.","Balanced landing on every rep.","No sidearm push throws."],"progression":["Regression: plant-and-throw without jump.","Base: full jump-throw.","Advanced: on-the-run into the LF grass."]}'::jsonb),
('baseball','Relay Footwork','Cut down runners with a clean CF-to-plate relay and full body rotation.','Relay rule: catch on your glove side, throw across your body.',6,ARRAY['SS','2B','MI'],ARRAY['infield','throwing_accuracy'],
 '{"purpose":"Convert extra-base hits into outs at 3B or home with a clean, fast relay throw.","setup":["OF partner throws from 200 ft. Relay fielder aligned with target base.","15 reps to home, 15 to 3B."],"execution":["Face the outfielder, glove-side facing the target base.","Catch on the glove side; throwing-shoulder rotates through the target.","Release without a wind-up; carry momentum through the finish."],"coaching_cues":["Glove side to the ball","Feet aim the throw","Rotate through, don\u2019t stop","One-hop the plate every time"],"mistakes":["Catching across the body (kills rotation).","Full wind-up before release.","Air-mailing instead of one-hopping the plate."],"success_markers":["Glove-side catch on ≥14/15 reps.","One-hop to plate on ≥12/15 reps.","No stopped throws."],"progression":["Regression: dry footwork, no throw.","Base: partner relay.","Advanced: full OF-to-plate live scenario."]}'::jsonb),
('baseball','Tag-and-Tap DP Finish','Save DPs by knowing when to tag first, then throw.','Slow runner + short throw = tag first. Fast runner + long throw = feed first.',6,ARRAY['2B','SS','MI'],ARRAY['infield','fielding_mechanics'],
 '{"purpose":"Choose the correct DP finish based on runner speed and throw distance.","setup":["Runner or cone at 2B, feeder at SS. 12 reps: 6 tag-first, 6 feed-first."],"execution":["Read the runner\u2019s jump before catching the feed.","Tag-first: sweep past the bag, then throw.","Feed-first: catch on the bag, clear slide lane, throw."],"coaching_cues":["Read the runner first","Sweep with the tag","Throw from a strong platform","Never lose the ball on the transfer"],"mistakes":["Tagging late (already thrown).","Standing on the bag for the throw.","Rushing the wrong choice."],"success_markers":["Correct choice on ≥10/12 reps.","On-line throw to 1B on ≥8/12 reps.","No dropped transfers."],"progression":["Regression: coach calls choice out loud.","Base: read the runner.","Advanced: live runner sliding hard."]}'::jsonb),
('baseball','First-Step Reactive Drops','Sharpen the first-step read that turns line drives into outs.','Elite reads happen at the pitcher''s release, not the crack of the bat.',6,ARRAY['2B','SS','MI','3B','1B','CI','IF'],ARRAY['infield','fielding_mechanics'],
 '{"purpose":"Sharpen the first-step read that separates elite infielders from average ones.","setup":["Coach with tennis balls at 45 ft. 30 rapid reps — mix of grounders, liners, and pop-ups above shoulder height."],"execution":["Athletic stance, small pre-pitch hop timed to release.","Read hop or trajectory in 0.1 s and take a direct first step.","Field or catch, reset, repeat."],"coaching_cues":["Small hop on release","Read before you move","Direct first step — no false step","Reset, don\u2019t admire"],"mistakes":["False step backward on grounders.","Frozen feet on liners.","Chasing a bad first step instead of resetting."],"success_markers":["Direct first step on ≥25/30 reps.","Clean field/catch on ≥22/30 reps.","Consistent pre-pitch hop across the set."],"progression":["Regression: 15 reps, half tempo.","Base: 30 rapid reps.","Advanced: paired with a partner competitor."]}'::jsonb),
('baseball','3B In-at-the-Line Reactions','Own the line by turning smash line drives into outs with a fearless first move.','3B rule: nothing gets past you when guarding the line.',7,ARRAY['3B','CI','IF'],ARRAY['infield','fielding_mechanics'],
 '{"purpose":"Turn smash line drives at 3B into outs when guarding the line late in a game.","setup":["Coach short-tosses balls at 35 ft with a controlled fungo. 20 reps: 10 backhand smash, 10 diving in."],"execution":["Feet at line depth, weight forward on the balls of the feet.","On smash: extend backhand or drop to block with the chest.","On diving in: attack the ball with soft hands, roll through."],"coaching_cues":["Chest at the ball","Trust the backhand","Roll through the dive","Get up throwing"],"mistakes":["Pulling the head off the ball.","Reaching sideways instead of attacking.","Standing after a dive without a throw."],"success_markers":["Ball stopped or caught on ≥16/20 reps.","Recovery to feet with ball secured on every dive.","Backhand secure on ≥8/10 smash reps."],"progression":["Regression: soft-toss reads.","Base: 35 ft fungoes.","Advanced: live BP down the line."]}'::jsonb),
('baseball','1B Pick Ladder','Turn errant throws into scoops with the right hand for each hop.','1B pick rule: one hop → step and scoop; short hop → drop and pick; in-between → backhand or block.',6,ARRAY['1B','CI','IF'],ARRAY['infield','fielding_mechanics'],
 '{"purpose":"Catch every throw at 1B, on every hop, so infielders trust the throw.","setup":["Partner throws from SS position (short, in-between, long hops). 30 reps: 10 of each hop type."],"execution":["Set foot on the bag, weight ready to shift.","Short-hop: drop to a knee, scoop with mitt open low.","In-between: turn the mitt backhand or block with the chest.","Long-hop: catch out in front."],"coaching_cues":["Foot on the bag, weight loaded","Drop early on short hops","Backhand the in-between","Stretch on the long hop"],"mistakes":["Reaching for a short hop and letting it eat you up.","Falling off the bag on stretches.","Stabbing in-between hops."],"success_markers":["Scoop or catch on ≥25/30 reps.","No pulled feet off the bag.","Correct pick style on ≥85% of reps."],"progression":["Regression: partner throws only short hops.","Base: mixed ladder.","Advanced: rapid-fire ladder from short throws."]}'::jsonb),
('baseball','1B Footwork Off the Bag','Give infielders more room to throw by clearing the bag correctly on off-line throws.','Move the feet before the ball forces you to.',6,ARRAY['1B','CI','IF'],ARRAY['infield','fielding_mechanics'],
 '{"purpose":"Give the infielder more room to throw and save errors on off-line throws.","setup":["Partner throws from SS. 20 reps: 5 inside line, 5 outside line, 5 short, 5 wide-arm-side."],"execution":["Read throw path early and clear the bag with a quick shuffle.","Reach for the ball while staying on the base with any part of the foot.","Recover balance without stepping off."],"coaching_cues":["Move feet before the ball moves you","Reach with the glove, not the body","Keep any part of the foot on the bag","Land balanced"],"mistakes":["Sticking to the bag on wide throws.","Losing the bag on the reach.","Reaching before setting feet."],"success_markers":["Bag maintained on ≥18/20 reps.","Off-line throws saved on ≥14/20 reps.","Balanced recovery on every rep."],"progression":["Regression: dry footwork.","Base: 20-rep mixed set.","Advanced: rapid set with live runners."]}'::jsonb),
('baseball','3-6-3 Turn','Force force-outs at 2B and race back to 1B for a clean DP.','Feet lead the throw both directions.',7,ARRAY['1B','CI','IF'],ARRAY['infield','throwing_accuracy'],
 '{"purpose":"Turn a 3-6-3 double play under game pressure without a dropped feed.","setup":["Coach fungoes grounders to 1B; SS covers second. 12 reps."],"execution":["Field grounder, plant on throwing-side foot.","Throw over the runner\u2019s helmet to the SS at 2B.","Sprint back to the bag with mitt open for return throw."],"coaching_cues":["Field, plant, throw over the helmet","Sprint, don\u2019t jog back","Present mitt early","Foot on the bag, chest up"],"mistakes":["Throwing sidearm into the runner\u2019s slide lane.","Jogging back to 1B and missing the return.","Late presentation of the mitt."],"success_markers":["Throw on-line to SS on ≥10/12 reps.","Return catch made on ≥10/12 reps.","Bag secured on every rep."],"progression":["Regression: dry throw+run.","Base: full 3-6-3.","Advanced: with real runners."]}'::jsonb),
('baseball','Bunt Charge — Barehand-and-Throw','Beat the runner on a sac bunt with a fearless barehand charge from the corner.','Charge angle keeps you inside the runner\u2019s path.',6,ARRAY['1B','3B','CI','IF'],ARRAY['infield','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Convert bunts on the corners into 1B outs with a barehand charge.","setup":["Coach bunts balls in the corner lanes. 15 reps."],"execution":["Charge at a 45\u00b0 angle inside the runner\u2019s path.","Field with barehand on the outside of the ball.","Throw off the plant foot without stopping."],"coaching_cues":["Charge inside the runner","Barehand outside the ball","Throw off the plant","Follow through to the base"],"mistakes":["Charging directly at the ball (fielder runs through it).","Full stop before throw.","Two-hand attempt on a fast bunt."],"success_markers":["Barehand secure on ≥12/15 reps.","On-line throw to 1B on ≥10/15 reps.","No collision with runner."],"progression":["Regression: barehand dry drill.","Base: live bunts.","Advanced: with real runners."]}'::jsonb),
('baseball','Corner Tag Plays','Convert steal attempts and pickoffs into outs with a legal, quick tag.','Ball first — tag second — show the umpire.',5,ARRAY['1B','3B','CI','IF'],ARRAY['infield','fielding_mechanics'],
 '{"purpose":"Apply clean tags on steals and pickoffs at 1B/3B without dropping the ball.","setup":["Partner throws from various infield spots. Runner or pad slides. 20 reps."],"execution":["Straddle the base with feet outside the slide lane.","Receive the ball, drop the glove flat between runner and bag.","Present ball to umpire after tag."],"coaching_cues":["Feet outside the lane","Ball first, tag second","Sweep, don\u2019t chop","Show the ump"],"mistakes":["Blocking the bag before the ball.","Chasing the tag away from the base.","Dropping the ball on impact."],"success_markers":["Ball secured on ≥18/20 tags.","No blocked-bag calls.","Umpire-facing presentation on every rep."],"progression":["Regression: stationary tag.","Base: sliding pad.","Advanced: real runner with cleats."]}'::jsonb),
('baseball','Drop-Step & Crossover Reads','Turn deep flies into caught balls with a first-step drop that eats ground.','Elite OF read: turn your hips before your feet leave the ground.',5,ARRAY['LF','CF','RF','OF'],ARRAY['outfield','fielding_mechanics'],
 '{"purpose":"Get to deep flies with a first-step drop that opens the hips and covers ground.","setup":["Coach fungoes deep balls with random direction. 20 reps."],"execution":["Read ball off the bat with a tiny pre-pitch hop.","On deep read: drop-step with the direction foot, cross over with the far foot.","Run on the balls of the feet with head still, then peek and catch."],"coaching_cues":["Turn hips, not head","Drop-step, then cross","Run first, look second","Catch out in front"],"mistakes":["Back-pedaling instead of turning.","Head bouncing while running.","Late peek — ball lands short of you."],"success_markers":["Direct first step on ≥18/20 reps.","Catch on ≥15/20 reps.","No back-pedaling on deep reads."],"progression":["Regression: dry footwork.","Base: full fungoes.","Advanced: fungoes with wind + sun."]}'::jsonb),
('baseball','Over-the-Shoulder Catches','Convert the hardest OF play — the ball running over your shoulder — into a routine catch.','Keep the ball in your peripheral, run in a straight line.',6,ARRAY['LF','CF','RF','OF'],ARRAY['outfield','fielding_mechanics'],
 '{"purpose":"Catch balls running over the glove-side and arm-side shoulder without breaking stride.","setup":["Coach lofts balls that force a full sprint over each shoulder. 20 reps (10 each side)."],"execution":["Take an efficient angle at first sight of the ball.","Keep ball in peripheral vision without turning the head fully.","Extend glove hand at the last second, snap ball into pocket."],"coaching_cues":["Run in a straight line","Ball in the peripheral","Late glove","Secure and reset"],"mistakes":["Angle too flat — ball lands behind the fielder.","Head turned fully, breaking stride.","Reaching too early."],"success_markers":["Straight-line run on ≥18/20 reps.","Catch on ≥14/20 reps.","No broken strides."],"progression":["Regression: shorter fungos.","Base: 20-rep full set.","Advanced: with a runner tag-up scenario."]}'::jsonb),
('baseball','Do-or-Die Charge — One-Hop','Save a run on a base hit by charging, fielding, and long-hopping the plate in one motion.','Charge angle first — release mechanics second.',6,ARRAY['LF','CF','RF','OF'],ARRAY['outfield','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Save a run at the plate with a full-speed charge and a long-hop throw home.","setup":["Coach hits ground balls in front of the OF at 250 ft from home. 15 reps."],"execution":["Charge at full speed, glove-side foot leads on approach.","Field with two hands or glove-only on the run.","Crow-hop and release with a long low-hop trajectory to the plate."],"coaching_cues":["Charge, don\u2019t drift","Field and release in one motion","Long hop, not air mail","Finish through the target"],"mistakes":["Waiting for the ball to slow.","Fielding one-handed when two would work.","Air-mailing the cutoff."],"success_markers":["Field-and-release in ≤1.8 s on ≥12/15 reps.","Long-hop to plate on ≥10/15 reps.","On-line to cutoff on the rest."],"progression":["Regression: field + step + throw.","Base: full do-or-die.","Advanced: with catcher receiving live."]}'::jsonb),
('baseball','Wall Reads and Caroms','Convert doubles into singles by reading the ball off the wall.','Ball reading matters more than jumping — read carom, then react.',6,ARRAY['LF','CF','RF','OF'],ARRAY['outfield','fielding_mechanics'],
 '{"purpose":"Convert wall-ball doubles into singles by reading the carom before it happens.","setup":["Coach throws or fungoes balls off an outfield wall. 15 reps at various angles."],"execution":["Sprint to the spot, drift-brake before the wall.","Turn to face the field and read the carom off the wall angle.","Field on the run and set for a strong throw to 2B."],"coaching_cues":["Beat the ball to the wall","Turn and read","Two hands or barehand on the fast carom","Throw to 2B, not to the moon"],"mistakes":["Colliding with the wall on the sprint.","Backpedaling into the wall.","Missing the carom because eyes were on the wall."],"success_markers":["Ball secured on ≥12/15 reps.","No wall collisions.","On-line throw to 2B on ≥10/15 reps."],"progression":["Regression: rolled balls off wall.","Base: fungoes.","Advanced: unpredictable spin off wall."]}'::jsonb),
('baseball','Cutoff Communication Grid','Prevent extra bases with clear cutoff calls and lined-up throws.','Elite OF: one voice, one line, one target.',5,ARRAY['LF','CF','RF','OF','2B','SS','1B','3B','MI','CI','IF'],ARRAY['outfield','throwing_accuracy'],
 '{"purpose":"Prevent runner advancement with rehearsed cutoff communication.","setup":["Full outfield + infield setup. Coach hits balls to specific scenarios. 12 reps: 4 singles, 4 doubles, 4 sac flies."],"execution":["OF secures ball and immediately calls target base.","Cutoff aligns between OF and target base, adjusts to keep throw in-line.","Cutoff decides: cut or let go, then executes."],"coaching_cues":["Loud, one voice","Line up with the target base","Cut or let go — decide fast","Trail the play if you didn\u2019t catch it"],"mistakes":["Silent OF — infield guesses.","Cutoff drifts out of the throw line.","Cutoff cuts a ball that should have gone through."],"success_markers":["Verbal call on 100% of plays.","Cutoff aligned on ≥10/12 reps.","Correct cut/let-go decision on ≥10/12 reps."],"progression":["Regression: walk-through with no throws.","Base: 12-rep scenario grid.","Advanced: full-speed live with runners."]}'::jsonb),
('baseball','Sliding vs Diving Decision Reps','Choose the right shoe-tops technique — slide catch or dive — every time.','Slide when you have time, dive only when you don\u2019t.',6,ARRAY['LF','CF','RF','OF'],ARRAY['outfield','fielding_mechanics'],
 '{"purpose":"Choose the correct shoe-tops technique (slide or dive) based on distance and angle.","setup":["Coach lofts short liners at various angles. 20 reps."],"execution":["Read hang time on first step.","Slide when 2+ steps early: bend knees, slide feet-first, glove out.","Dive only when late: lay out flat with glove extended full-length."],"coaching_cues":["Time decides — slide or dive","Feet-first on slides","Full extension on dives","Roll through and pop up"],"mistakes":["Diving when you had time to slide (injury risk).","Sliding when you needed to dive (ball drops).","Reaching without full extension."],"success_markers":["Correct choice on ≥16/20 reps.","Catch on ≥14/20 reps.","Recovery to feet with ball on every rep."],"progression":["Regression: walk-through choice.","Base: live fungoes.","Advanced: mixed with wind + sun."]}'::jsonb),
('baseball','High-Fly Reads Under Fatigue','Kill the late-game dropped fly by drilling reads while tired.','Fatigue is when routine flies become adventures.',6,ARRAY['LF','CF','RF','OF'],ARRAY['outfield','fielding_mechanics'],
 '{"purpose":"Keep routine flies routine in late innings when the legs and eyes get tired.","setup":["Coach fungoes 3 rounds of 8 high flies with 20 sprints between rounds."],"execution":["Every catch is thrown to a designated relay.","Same read process every rep: hop-read-run-catch.","Log any hesitation or drop."],"coaching_cues":["Same read every rep","Get under it, then reset","Trust your feet","Nothing changes when you\u2019re tired"],"mistakes":["Coasting under fatigue.","Skipping the pre-pitch hop.","Reaching instead of getting under the ball."],"success_markers":["Catch on ≥21/24 reps.","No coasted reads across the set.","Sprint intensity maintained between rounds."],"progression":["Regression: 2-round version.","Base: 3-round full circuit.","Advanced: add wind + sun."]}'::jsonb),
('baseball','1-3 Cover First','Own the 1-3 cover with a clean angle, banana route, and glove-side pick.','Banana route lets the throw meet you at the bag.',5,ARRAY['P','PFP'],ARRAY['pitcher_fielding','fielding_mechanics'],
 '{"purpose":"Convert groundballs to the 1B side into outs with clean 1-3 cover technique.","setup":["Coach fungoes grounders to 1B. Pitcher covers on every rep. 15 reps."],"execution":["Break for the base on ball contact.","Run a banana route to arrive parallel to the first base line.","Catch throw on the glove side 2\u20133 steps before the bag, tag with the right foot on the inside corner."],"coaching_cues":["Banana route","Glove-side catch","Right foot inside corner","Peek at the bag, don\u2019t stare"],"mistakes":["Straight-line route → collision or across-body catch.","Reaching for ball with body twisted.","Stepping on the runner\u2019s foot line."],"success_markers":["Bag hit cleanly on ≥13/15 reps.","No collisions or runner interference.","Ball secured on every rep."],"progression":["Regression: dry footwork route.","Base: full 1-3.","Advanced: with real runner."]}'::jsonb),
('baseball','Comebackers to Second','Turn comebackers into DPs with a clean read and accurate feed to 2B.','Field, plant, throw over the top — no side-arm rushed feeds.',6,ARRAY['P','PFP'],ARRAY['pitcher_fielding','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Turn comebackers into DPs with a clean field and accurate feed to 2B.","setup":["Coach hits sharp comebackers. 12 reps."],"execution":["Field the ball with body squared to the plate.","Plant on throwing-side foot pointing at 2B.","Release over the top with a firm 4-seam grip."],"coaching_cues":["Get behind the ball","Plant, then throw","Over the top, not side-arm","Follow through toward 2B"],"mistakes":["Sidearm rushed feed → tail into the runner.","Throwing off the wrong foot.","Not planting before release."],"success_markers":["On-line feed on ≥10/12 reps.","No sidearm reps.","Balanced release on every rep."],"progression":["Regression: dry throw to 2B.","Base: fungoed comebackers.","Advanced: live BP comebackers."]}'::jsonb),
('baseball','PFP Bunt Coverage','Cover bunts with a clean charge and decisive throwing choice.','Elite pitcher: charge → field → set feet → throw to the correct base.',5,ARRAY['P','PFP'],ARRAY['pitcher_fielding','fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Cover bunts fielding lane responsibly and throw to the correct base under pressure.","setup":["Coach bunts balls into the pitcher\u2019s lane. 15 reps: 5 sac to 1B, 5 sac to 2B, 5 squeeze to home."],"execution":["Break to the ball with mitt-first approach.","Field with two hands and immediately square feet to target.","Deliver a firm on-line throw."],"coaching_cues":["Mitt to the ball first","Square feet before throw","Loud call to yourself","Take the sure out"],"mistakes":["Barehanding a ball you had time to two-hand.","Throwing off the wrong foot.","Choosing wrong base under pressure."],"success_markers":["Two-hand field on ≥12/15 reps.","Correct base decision on ≥13/15 reps.","On-line throw on ≥12/15 reps."],"progression":["Regression: walk-through decisions.","Base: 15-rep set.","Advanced: with real runners + coach calling base."]}'::jsonb),
('baseball','Backing Up Bases','Prevent extra bases by hustling to your backup spot on every ball in play.','No pitcher stands still on a ball in play.',4,ARRAY['P','PFP'],ARRAY['pitcher_fielding','fielding_mechanics'],
 '{"purpose":"Prevent extra bases on overthrows by getting to the correct backup spot every time.","setup":["Coach hits balls to all fields. Pitcher must get to backup spot on 12 reps."],"execution":["On ball hit, immediately identify backup base (3B or home).","Sprint 30\u201340 ft behind the base in line with the throw.","Get low to field a bad hop off the fence."],"coaching_cues":["Move on contact","Line up with the throw","30\u201340 feet deep","Get low on the backup"],"mistakes":["Standing on the mound admiring the play.","Wrong angle — ball skips past.","Standing too close to the base."],"success_markers":["Correct backup spot on ≥11/12 reps.","Distance ≥30 ft on every rep.","Ready position on arrival."],"progression":["Regression: walk-through cadence.","Base: 12-rep set.","Advanced: with real overthrows."]}'::jsonb),
('baseball','PFP Pickoff Timing — 1B/2B','Deliver quick, accurate pickoff throws with slide-step timing.','Elite pickoff: quick, not fast — deception + accuracy.',6,ARRAY['P','PFP'],ARRAY['pitcher_fielding','throwing_accuracy'],
 '{"purpose":"Steal outs with quick, accurate pickoff throws that keep runners honest.","setup":["Coach as runner at 1B or 2B. Pitcher works from stretch. 20 reps: 10 to 1B, 10 to 2B."],"execution":["Vary hold times (0.8\u20131.8 s) to disrupt runner rhythm.","1B pickoff: quick jump-turn, throw over the top to the inside of the bag.","2B pickoff: use a daylight play or timing play with SS/2B."],"coaching_cues":["Vary the hold","Jump-turn quick, not fast","Inside corner of the bag","Deception in the shoulders"],"mistakes":["Same hold time every rep (runner reads it).","Balking on the pickoff.","Air-mailing the middle infielder."],"success_markers":["No balks.","On-target throw on ≥16/20 reps.","Runner disrupted on ≥12/20 reps."],"progression":["Regression: pickoff without a runner.","Base: coach as runner.","Advanced: real base-stealer competing."]}'::jsonb),
('baseball','4-Seam Grip Re-set on the Fly','Guarantee a 4-seam grip on every throw for on-line, non-tailing carry.','A tailing throw is a grip problem, not an arm problem.',4,ARRAY['P','C','1B','2B','3B','SS','LF','CF','RF','IF','OF','PFP','MI','CI'],ARRAY['fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Guarantee a 4-seam grip on every throw so the ball carries straight and true.","setup":["Coach fungoes to various positions. 25 reps."],"execution":["Field the ball, then feel for 4-seam horseshoe as the mitt travels to the throwing hand.","If grip is bad, spin the ball in the hand during the load — do NOT throw with a bad grip.","Release only when 4-seam is locked."],"coaching_cues":["Feel the horseshoe","Spin, don\u2019t throw a bad grip","Grip on the way up","Same grip every throw"],"mistakes":["Throwing a 2-seam grip by accident (ball tails).","Regripping after release-load starts (rushes throw).","Skipping the feel step."],"success_markers":["4-seam grip on ≥23/25 reps.","No tailing throws.","No dropped exchanges due to regrip."],"progression":["Regression: dry grip drills.","Base: 25-rep field-and-throw set.","Advanced: rapid-fire fungoes."]}'::jsonb),
('baseball','Crow-Hop Consistency Test','Standardize the crow-hop so throws carry with the same effort every time.','Elite thrower: same footwork = same arm slot = same accuracy.',5,ARRAY['LF','CF','RF','OF','P','C','1B','2B','3B','SS','IF','PFP','MI','CI'],ARRAY['fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Standardize the crow-hop so every long throw has the same rhythm and accuracy.","setup":["Partner at 150 ft. 20 throws with a video camera tracking footwork."],"execution":["Field or catch simulated ball, take one skip-hop that clears the throwing-side foot in front of the glove-side foot.","Land balanced, release from a full arm circle.","Recover forward, not falling back."],"coaching_cues":["One hop — no more, no less","Clear the throwing foot","Full arm circle","Follow through toward the target"],"mistakes":["Multiple hops that kill the rhythm.","Falling back on release.","Short-arm release that kills carry."],"success_markers":["Same footwork on ≥18/20 reps (video review).","On-line throw on ≥16/20 reps.","No falling-back releases."],"progression":["Regression: dry crow-hops.","Base: 150-ft catch play.","Advanced: full 200+ ft carry throws."]}'::jsonb),
('baseball','Priority Call Sequences','Prevent collisions and dropped popups with rehearsed priority calls.','Priority hierarchy: CF > corner OF > MI > CI > P > C.',4,ARRAY['LF','CF','RF','OF','2B','SS','1B','3B','P','C','IF','MI','CI'],ARRAY['fielding_mechanics'],
 '{"purpose":"Prevent collisions and dropped popups on shared coverage areas.","setup":["Full team on field. Coach hits popups in gap zones. 12 reps."],"execution":["Loud, early, repeated call: \"I got it! I got it!\"","Deferring player calls: \"You! You! You!\" and clears the zone.","Priority hierarchy: CF > corner OF > MI > CI > P > C."],"coaching_cues":["Loud, early, three times","Clear the zone if you\u2019re not on the ball","Center fielder is king","No silent catches"],"mistakes":["Silent calls or single-word calls.","No deferring call from the other fielder.","Ignoring priority hierarchy."],"success_markers":["Two-way verbal call on 100% of reps.","No collisions or near-misses.","Correct priority winner on ≥11/12 reps."],"progression":["Regression: walk-through with verbal only.","Base: 12-rep popup set.","Advanced: with wind + sun."]}'::jsonb),
('baseball','On-Line Footwork Ladder','Build automatic on-line throwing footwork after a field or catch.','If the plant foot is on line, the throw is on line.',4,ARRAY['P','C','1B','2B','3B','SS','LF','CF','RF','IF','OF','PFP','MI','CI'],ARRAY['fielding_mechanics','throwing_accuracy'],
 '{"purpose":"Automate on-line throwing footwork so accuracy survives all fielding chaos.","setup":["Coach flips balls at random distances. Fielder throws to a target net at 60 ft. 20 reps."],"execution":["Field or catch, then take a directional replace step aiming plant foot at target.","Release with foot on line and follow-through past the target.","Reset and repeat."],"coaching_cues":["Plant foot decides the throw","Directional replace","Follow through past the target","Reset, don\u2019t admire"],"mistakes":["Throwing across the body.","Plant foot off-line by 15\u00b0+.","No follow-through."],"success_markers":["Plant foot on line on ≥18/20 reps (video).","Throw hits target zone on ≥16/20 reps.","No cross-body throws."],"progression":["Regression: dry footwork.","Base: 20-rep flip-and-throw.","Advanced: rapid-fire under fatigue."]}'::jsonb)
),
inserted AS (
  INSERT INTO public.drills (
    name, module, sport, description, ai_context,
    progression_level, difficulty_levels, premium,
    is_active, is_published, instructions, subscription_tier_required
  )
  SELECT
    s.name,
    CASE WHEN 'PFP' = ANY(s.positions) THEN 'throwing' ELSE 'fielding' END,
    s.sport,
    s.description,
    s.ai_context,
    s.level,
    ARRAY['intermediate','advanced'],
    true, true, true,
    s.instructions,
    'premium'
  FROM seed s
  WHERE NOT EXISTS (
    SELECT 1 FROM public.drills d WHERE d.name = s.name AND d.sport = s.sport
  )
  RETURNING id, name, sport
),
pos_ins AS (
  INSERT INTO public.drill_positions (drill_id, position)
  SELECT i.id, unnest(s.positions)
  FROM inserted i JOIN seed s ON s.name=i.name AND s.sport=i.sport
  ON CONFLICT (drill_id, position) DO NOTHING
  RETURNING drill_id
),
tag_ins AS (
  INSERT INTO public.drill_tag_map (drill_id, tag_id, weight)
  SELECT i.id, dt.id, 1
  FROM inserted i
  JOIN seed s ON s.name=i.name AND s.sport=i.sport
  CROSS JOIN LATERAL unnest(s.tag_names) AS tn(tag_name)
  JOIN public.drill_tags dt ON dt.name = tn.tag_name
  ON CONFLICT (drill_id, tag_id) DO NOTHING
  RETURNING drill_id
)
SELECT count(*) AS drills_inserted FROM inserted;
